"""
Reemplaza los párrafos genéricos de teoría en las 21 secciones compactas
con contenido real de dominio basado en la research del agente R2.
También reemplaza el código placeholder del I Do con código real.
"""
import os

# Contenido real para cada sección: (heading, [3 paragraphs], code_title, code_content, why)
SECTIONS = {
    's30-security-infra': {
        'paragraphs': [
            'Zero Trust Architecture (ZTA) elimina el modelo de "castle and moat" donde todo dentro de la red corporativa era confiable. En ZTA, cada request debe autenticarse y autorizarse sin importar su origen. Para pipelines de IA, esto significa mTLS entre microservicios con certificados firmados por una CA interna, JWT firmados con RS256 para autenticación, y RBAC estricto en cada endpoint. Herramientas como HashiCorp Vault centralizan la gestión de secretos con rotación automática, eliminando el riesgo de API keys hardcodeadas en código o variables de entorno.',
            'El OWASP API Top 10 (2023) identifica BOLA (Broken Object Level Authorization) como la vulnerabilidad #1 en APIs. En pipelines de IA, esto significa que un usuario no debe poder acceder a predicciones de otro usuario sin autorización explícita. La mitigación implementa checks de autorización a nivel de objeto en cada endpoint, no solo a nivel de endpoint. En Python FastAPI, esto se logra con dependencies que verifican ownership antes de retornar datos: `if resource.owner_id != current_user.id: raise HTTPException(403)`.',
            'El logging de auditoría con structlog es esencial para compliance y forense. structlog produce logs JSON estructurados con campos como timestamp, user_id, endpoint, ip, response_code, y duration_ms. Esto permite queries eficientes en ELK/Datadog: "muéstrame todos los requests al endpoint /predict desde IP X en las últimas 24h". Sin logs estructurados, investigar un incidente de seguridad es como buscar una aguja en un pajar de texto plano. La regla: cada acción de seguridad (login, acceso a datos sensibles, cambio de configuración) debe loggearse con nivel INFO mínimo.',
        ],
        'code_title': 'vault_security.py',
        'code_content': '"""Seguridad Zero Trust para microservicios de IA."""\nimport hvac\nimport structlog\nfrom cryptography.fernet import Fernet\n\nlogger = structlog.get_logger()\n\n# 1. Vault para secretos\nvault = hvac.Client(url=os.environ["VAULT_ADDR"], token=os.environ["VAULT_TOKEN"])\ndef get_secret(path: str) -> str:\n    """Obtiene un secreto desde Vault con auditoría."""\n    logger.info("secret_accessed", path=path, service="ml-pipeline")\n    return vault.secrets.kv.v2.read_secret_version(path=path)["data"]["data"]["value"]\n\n# 2. Cifrado PII\nkey = Fernet.generate_key()\ncipher = Fernet(key)\ndef encrypt_pii(data: str) -> bytes:\n    """Cifra datos PII antes de almacenarlos."""\n    return cipher.encrypt(data.encode())',
        'why': 'Vault centraliza secretos con rotación automática y auditoría. structlog da logs JSON queryable para forense. Fernet cifra PII con AES-128-CBC + HMAC.',
    },
    's31-streaming-data': {
        'paragraphs': [
            'Apache Kafka es el estándar de facto para streaming de datos a escala. Un cluster Kafka tiene brokers (servidores), topics (canales de datos), producers (quienes escriben), y consumers (quienes leen). Para Python, confluent-kafka-python es el cliente más robusto con soporte para Avro serializers y schema registry. Un producer envía eventos con `producer.produce(topic, key, value, callback)` — el callback se ejecuta async cuando el broker confirma. Para exactly-once semantics (EOS), Kafka 3.x+ requiere `enable.idempotence=true` en el producer y `isolation.level=read_committed` en el consumer.',
            'El procesamiento de streams requiere windowing: agrupar eventos por tiempo. Tumbling windows son no superpuestas (cada 5 min, un batch completo). Sliding windows se superponen (ventana de 10 min que avanza cada 5 min — útil para medias móviles). Session windows agrupan por actividad con gap de inactividad (sesión de usuario). En Python, Faust o aiokafka implementan estos patrones. El truco clave: siempre usa `consumer.commit()` manualmente después de procesar exitosamente — nunca auto-commit, porque si el consumer crashea entre leer y procesar, pierdes datos.',
            'Backpressure es el problema #1 en streaming. Si el producer produce 10K msg/seg pero el consumer solo procesa 1K, la queue crece hasta OOM. asyncio.Queue(maxsize=N) soluciona esto: cuando la queue está llena, `await queue.put(item)` bloquea al producer hasta que haya espacio. Esto es backpressure natural. En Kafka, se controla via `max.poll.records` y `fetch.max.bytes` para limitar cuántos registros consume el consumer por poll. Monitorea `consumer-lag` con Burrow o Kafka UI — si crece, necesitas más consumers o procesamiento más rápido.',
        ],
        'code_title': 'kafka_producer.py',
        'code_content': '"""Productor Kafka con exactly-once semantics."""\nfrom confluent_kafka import Producer, KafkaException\nimport json\n\nconf = {\n    "bootstrap.servers": "localhost:9092",\n    "enable.idempotence": True,  # Exactly-once\n    "acks": "all",\n    "retries": 2147483647,\n    "max.in.flight.requests.per.connection": 5,\n}\nproducer = Producer(conf)\n\ndef delivery_report(err, msg):\n    """Callback async de confirmación."""\n    if err:\n        print(f"Error: {err}")\n    else:\n        print(f"Enviado a {msg.topic()} partition {msg.partition()}")\n\n# Enviar evento de transacción\nevent = {"user_id": 123, "amount": 150.0, "timestamp": "2026-07-14T10:00:00Z"}\nproducer.produce("transactions", \n                 key=str(event["user_id"]),\n                 value=json.dumps(event).encode(),\n                 callback=delivery_report)\nproducer.flush()  # Esperar todas las confirmaciones',
        'why': 'enable.idempotence=True garantiza exactly-once: Kafka deduplica reintentos automáticamente. acks=all asegura que el evento se persiste en múltiples réplicas antes de confirmar.',
    },
    's32-microservices': {
        'paragraphs': [
            'La arquitectura de microservicios divide una aplicación monolítica en servicios independientes que se comunican via APIs. Cada microservicio tiene su propia base de datos, su propio ciclo de deploy, y puede escalar independientemente. En Python, FastAPI es el framework preferido por su velocidad (Starlette + Pydantic) y documentación automática OpenAPI. El trade-off principal: complejidad operacional. Un monolito se depura en un solo proceso; 10 microservicios requieren distributed tracing (Jaeger/Zipkin), logging centralizado (ELK), y service mesh (Istio/Linkerd) para mTLS y circuit breakers.',
            'Docker es el estándar para empaquetar microservicios. Un Dockerfile multi-stage para Python separa el entorno de build (con gcc, headers, dev deps) del runtime (solo Python + app). La imagen final usa `python:3.12-slim` como base y puede ser < 100MB. El truco clave: copia `requirements.txt` primero y instala deps antes de copiar el código — esto aprovecha el layer caching de Docker y hace que los builds sean rápidos cuando solo cambias código, no dependencias. Usa `.dockerignore` para excluir `venv/`, `__pycache__/`, `.git/`.',
            'Kubernetes (K8s) orquesta contenedores a escala. Un Deployment define cuántas réplicas quieres (ej. 3) y K8s mantiene ese estado deseado. Si un pod muere, K8s lo reinicia automáticamente. Un Service expone el Deployment internamente (ClusterIP) o externamente (LoadBalancer). Un Ingress publica el servicio al exterior con TLS termination. Para Python, los health checks son críticos: `/health` (liveness — el pod está vivo) y `/ready` (readiness — el pod puede recibir tráfico). Sin readiness probe, K8s envía tráfico a un pod que aún no ha cargado el modelo de ML.',
        ],
        'code_title': 'Dockerfile',
        'code_content': '# Dockerfile multi-stage para FastAPI + ML\nFROM python:3.12-slim AS builder\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\n\nFROM python:3.12-slim AS runtime\nWORKDIR /app\nCOPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages\nCOPY --from=builder /usr/local/bin /usr/local/bin\nCOPY . .\nEXPOSE 8000\nHEALTHCHECK --interval=30s --timeout=3s CMD curl -f http://localhost:8000/health || exit 1\nCMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]',
        'why': 'Multi-stage reduce la imagen 70% (de 900MB a 150MB). HEALTHCHECK permite a K8s saber si el contenedor está vivo. slim base elimina gcc y headers innecesarios en runtime.',
    },
    's33-advanced-models': {
        'paragraphs': [
            'XGBoost y LightGBM son los modelos de gradient boosting más usados en competiciones Kaggle y producción. XGBoost es más preciso pero más lento; LightGBM es 3-5x más rápido con precisión comparable. Los hiperparámetros críticos son: `n_estimators` (número de árboles, 100-1000), `max_depth` (profundidad, 3-10), `learning_rate` (0.01-0.3), `subsample` (0.6-1.0), y `colsample_bytree` (0.6-1.0). Optuna usa TPE (Tree-structured Parzen Estimator) para explorar este espacio inteligentemente — encuentra el óptimo en 50 trials vs 500 de GridSearch, porque descarta regiones prometedoras rápidamente.',
            'Stacking ensembles combinan múltiples modelos base (LogisticRegression, RandomForest, XGBoost) via un meta-modelo que aprende cuándo confiar en cada uno. La clave es usar predicciones out-of-fold (cross-validation) como features del meta-modelo — si usas las mismas predicciones de entrenamiento, hay data leakage. mlxtend.StackingClassifier lo hace automáticamente. En producción, stacking da 2-5% de mejora sobre el mejor modelo individual, pero añade complejidad: necesitas serializar N+1 modelos y servirlos. Solo vale la pena si ese 2-5% tiene impacto de negocio (ej. detección de fraude donde cada punto de AUC ahorra miles de dólares).',
            'SHAP (SHapley Additive exPlanations) descompone una predicción en contribuciones por feature. Para XGBoost/RandomForest, `shap.TreeExplainer` es exacto y rápido. El beeswarm plot muestra importancia global: cada punto es una observación, color rojo = valor alto de la feature, azul = valor bajo, posición horizontal = impacto en la predicción. El waterfall plot explica una predicción individual: muestra cómo cada feature empuja la predicción desde el base value hasta el valor final. En entrevistas, saber interpretar SHAP es lo que diferencia un junior que "entrenó un modelo" de un senior que "entiende por qué el modelo predice lo que predice".',
        ],
        'code_title': 'optuna_xgb.py',
        'code_content': '"""Hyperparameter tuning con Optuna para XGBoost."""\nimport optuna\nimport xgboost as xgb\nfrom sklearn.model_selection import cross_val_score\n\ndef objective(trial):\n    params = {\n        "n_estimators": trial.suggest_int("n_estimators", 100, 500),\n        "max_depth": trial.suggest_int("max_depth", 3, 10),\n        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),\n        "subsample": trial.suggest_float("subsample", 0.6, 1.0),\n        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),\n    }\n    model = xgb.XGBClassifier(**params, random_state=42)\n    score = cross_val_score(model, X, y, cv=5, scoring="roc_auc").mean()\n    return score\n\nstudy = optuna.create_study(direction="maximize", pruner=optuna.pruners.MedianPruner())\nstudy.optimize(objective, n_trials=50)\nprint(f"Mejor AUC: {study.best_value:.4f}")\nprint(f"Mejores params: {study.best_params}")',
        'why': 'Optuna con TPE encuentra el óptimo en 50 trials vs 500 de GridSearch. MedianPruner descarta trials malos temprano, ahorrando 60% del tiempo de cómputo.',
    },
    's34-cv-ai-integration': {
        'paragraphs': [
            'YOLOv8 de Ultralytics es el modelo de detección de objetos más rápido y preciso para uso general. Puede detectar 80 clases del dataset COCO (persona, auto, perro, etc.) en 5ms por frame en GPU. Para usarlo en Python: `from ultralytics import YOLO; model = YOLO("yolov8n.pt"); results = model.predict("image.jpg")`. Los resultados incluyen bounding boxes, confianza, y clase para cada detección. Para video en tiempo real, itera frame por frame con OpenCV: `cap = cv2.VideoCapture(0); while cap.isOpened(): ret, frame = cap.read(); results = model.predict(frame)`.',
            'El OCR con Tesseract requiere preprocessing de OpenCV para ser útil en documentos reales. La cadena típica es: (1) convertir a grayscale, (2) aplicar adaptive threshold para binarizar, (3) deskew (corregir rotación) con `cv2.minAreaRect`, (4) denoise con `cv2.fastNlMeansDenoising`, (5) upscale 2x con `cv2.resize`. Sin este preprocessing, Tesseract tiene ~60% de precisión. Con él, llega a 85-90%. Para facturas peruanas, instala `tesseract-ocr-spa` (paquete de idioma español) — sin él, los acentos y la ñ se confunden sistemáticamente.',
            'La integración de visión computacional con LLMs abre posibilidades únicas. Por ejemplo: YOLOv8 detecta objetos en una escena (persona, mesa, laptop), luego un LLM (Ollama local o GPT-4V) genera una descripción natural: "Veo una persona sentada en una mesa con una laptop, parece estar trabajando". Esto es útil para accesibilidad (describir escenas para personas con discapacidad visual), monitoreo de seguridad (detectar intrusos y generar alertas contextuales), y análisis de retail (contar productos en góndolas y reportar quiebres de stock).',
        ],
        'code_title': 'yolo_detect.py',
        'code_content': '"""Detección de objetos en video con YOLOv8."""\nfrom ultralytics import YOLO\nimport cv2\n\nmodel = YOLO("yolov8n.pt")  # nano = más rápido, menos preciso\ncap = cv2.VideoCapture(0)  # Cámara web\n\nwhile cap.isOpened():\n    ret, frame = cap.read()\n    if not ret:\n        break\n    \n    # Detectar objetos (conf > 0.5)\n    results = model.predict(frame, conf=0.5, classes=[0])  # Solo personas\n    \n    # Anotar frame\n    annotated = results[0].plot()\n    \n    # Contar personas detectadas\n    count = len(results[0].boxes)\n    cv2.putText(annotated, f"Personas: {count}", (10, 30),\n                cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)\n    \n    cv2.imshow("YOLOv8", annotated)\n    if cv2.waitKey(1) & 0xFF == ord("q"):\n        break\n\ncap.release()\ncv2.destroyAllWindows()',
        'why': 'YOLOv8 procesa video en tiempo real (5ms/frame en GPU). El parámetro classes=[0] filtra solo personas, reduciendo falsos positivos. conf=0.5 balancea precisión y recall.',
    },
    's35-system-design': {
        'paragraphs': [
            'La arquitectura Lambda combina un batch layer (procesa TODO el histórico con MapReduce/Spark) y un speed layer (procesa streams en tiempo real con Kafka/Storm). Los resultados se mergean en una serving layer. La arquitectura Kappa simplifica Lambda eliminando el batch layer: todo es streaming. Si necesitas reprocesar histórico, simplemente replay el Kafka topic desde el inicio. En 2025-2026, Kappa es preferida porque reduce complejidad — un solo código base en vez de dos. Delta architecture (lakehouse con ACID) es la tercera opción: combina lo mejor de data lakes (escalabilidad, costo) y data warehouses (ACID, schema enforcement).',
            'Un feature store centraliza features para que sean consistentes entre training e inference. Sin feature store, tienes training-serving skew: el modelo se entrena con features calculadas de una forma, pero en producción se calculan diferente. Feast (open source) y Tecton (comercial) son las opciones principales. Feast define features en Python: `feature_view = FeatureView(name="user_features", features=[Feature("age", Int32), Feature("avg_spend", Float32)], source=batch_source)`. En training, `store.get_historical_features()` trae features point-in-time correctas. En inference, `store.get_online_features()` sirve features desde Redis en <10ms.',
            'Un Architecture Decision Record (ADR) documenta decisiones técnicas importantes: qué decidiste, por qué, y qué alternativas consideraste. El formato Michael Nygard es: (1) Context (qué problema resuelves), (2) Decision (qué decidiste), (3) Status (proposed/accepted/deprecated), (4) Consequences (qué implica). Los ADRs se guardan en `/docs/adr/` dentro del repo (no en Confluence — link rot). Cuando un nuevo engineer pregunta "¿por qué usamos Kafka en vez de RabbitMQ?", el ADR responde sin necesidad de buscar al autor original. Los equipos maduros tienen 50-100 ADRs que cuentan la historia técnica del proyecto.',
        ],
        'code_title': 'feast_feature_store.py',
        'code_content': '"""Feature store con Feast para consistencia training/serving."""\nfrom feast import FeatureStore, Entity, FeatureView, Feature\nfrom feast.types import Int32, Float32\nimport pandas as pd\n\n# Definir entidad y features\nuser = Entity(name="user_id", join_key="user_id")\n\nuser_features = FeatureView(\n    name="user_features",\n    entities=[user],\n    features=[\n        Feature(name="age", dtype=Int32),\n        Feature(name="avg_spend_30d", dtype=Float32),\n        Feature(name="login_count_7d", dtype=Int32),\n    ],\n    source=batch_source,\n)\n\n# Registrar\nstore = FeatureStore(repo_path=".")\nstore.apply([user, user_features])\n\n# Training: obtener features históricas point-in-time\nfeatures = store.get_historical_features(\n    entity_df=training_df,\n    features=["user_features:age", "user_features:avg_spend_30d"],\n).to_df()\n\n# Inference: obtener features online (<10ms)\nonline_features = store.get_online_features(\n    features=["user_features:age", "user_features:avg_spend_30d"],\n    entity_rows=[{"user_id": 123}],\n).to_dict()',
        'why': 'Feast elimina training-serving skew: las mismas features en training e inference. get_online_features sirve desde Redis en <10ms para inference en tiempo real.',
    },
    's36-ai-apis-advanced': {
        'paragraphs': [
            'Function calling con OpenAI API permite al LLM decidir qué función Python ejecutar basado en el contexto del usuario. Defines las funciones con schema JSON (nombre, descripción, parámetros), y el LLM responde con `tool_calls` indicando qué función llamar con qué argumentos. Por ejemplo, si el usuario pregunta "¿cuánto gastó el usuario 123 el mes pasado?", el LLM puede llamar `query_database(user_id=123, period="last_month")`. Tu código ejecuta la función, retorna el resultado al LLM, y el LLM genera una respuesta natural. Esto convierte al LLM en un orquestador inteligente que puede interactuar con bases de datos, APIs externas, y herramientas internas.',
            'Structured Outputs (agosto 2024) garantiza que el LLM devuelva JSON válido que parsea exactamente a tu modelo pydantic. Antes, usabas `response_format={"type": "json_object"}` que garantizaba JSON válido pero no el schema. Ahora, con `client.beta.chat.completions.parse(response_format=MyPydanticModel)`, el LLM respeta los tipos, campos requeridos, y validaciones de pydantic. Esto elimina el problema #1 de trabajar con LLMs en producción: parsear respuestas no estructuradas. Si el LLM no puede cumplir el schema, lanza `OutputParserException` en vez de devolver JSON roto.',
            'La Batch API de OpenAI procesa hasta 24h asíncrono con 50% de descuento vs synchronous API. Ideal para workloads no urgentes: clasificar 10,000 reviews de productos, extraer entidades de 50,000 documentos, o generar embeddings para 100,000 productos. Subes un archivo .jsonl donde cada línea es un request independiente. OpenAI procesa todo en paralelo internamente y te notifica cuando está listo. El resultado es otro .jsonl con las respuestas. Para un workload de 10K clasificaciones que costaría $200 síncrono, Batch cuesta $100 y completa en 2-4 horas.',
        ],
        'code_title': 'function_calling.py',
        'code_content': '"""Function calling con OpenAI API."""\nfrom openai import OpenAI\nimport json\n\nclient = OpenAI()\n\n# Definir herramientas disponibles\ntools = [{\n    "type": "function",\n    "function": {\n        "name": "query_database",\n        "description": "Consulta transacciones de un usuario",\n        "parameters": {\n            "type": "object",\n            "properties": {\n                "user_id": {"type": "integer", "description": "ID del usuario"},\n                "period": {"type": "string", "enum": ["day", "week", "month"]},\n            },\n            "required": ["user_id"],\n        },\n    },\n}]\n\n# El LLM decide si llamar la función\nresponse = client.chat.completions.create(\n    model="gpt-4o",\n    messages=[{"role": "user", "content": "Cuanto gasto el usuario 123 el mes pasado?"}],\n    tools=tools,\n)\n\nif response.choices[0].message.tool_calls:\n    call = response.choices[0].message.tool_calls[0]\n    args = json.loads(call.function.arguments)\n    print(f"Llamar query_database({args})")\n    # Ejecutar función real y retornar resultado al LLM',
        'why': 'Function calling permite al LLM orquestar herramientas externas. El LLM decide cuándo y cómo llamar cada función basado en el contexto del usuario.',
    },
    's37-dbt-bigquery': {
        'paragraphs': [
            'dbt (data build tool) transforma datos en SQL de forma declarativa y testeable. Un modelo dbt es un SELECT statement que se materializa como tabla, view, o incremental. La magia de dbt: define dependencias automáticamente (si modelo B hace JOIN con modelo A, dbt ejecuta A antes de B). Esto elimina el caos de scripts SQL con orden de ejecución manual. En BigQuery, dbt aprovecha partitioning (PARTITION BY date) y clustering (CLUSTER BY user_id) para optimizar queries y reducir costos. Una tabla particionada por fecha y consultada con `WHERE date >= CURRENT_DATE() - 7` cuesta 100x menos que un full scan.',
            'Los modelos incrementales son la clave para datasets grandes. Un modelo incremental solo procesa registros nuevos desde la última ejecución, no toda la tabla. Se configura con `materialized="incremental"` y un filtro temporal: `WHERE event_date > (SELECT max(event_date) FROM {{ this }})`. Sin `unique_key`, dbt hace INSERT (duplicados en re-runs). Con `unique_key="event_id"`, dbt hace MERGE (upsert). El error #1: olvidar `unique_key` y tener duplicados cada vez que el pipeline corre dos veces en un día.',
            'dbt tests validan integridad de datos en cada modelo. Los tests genéricos incluyen: `not_null` (la columna no tiene nulls), `unique` (no hay valores duplicados), `accepted_values` (solo ciertos valores permitidos), `relationships` (integridad referencial — cada foreign key existe en la tabla padre). Si un test falla, el pipeline se detiene con error. Esto previene que datos corruptos propaguen a dashboards y modelos de ML. La regla: cada columna crítica (IDs, fechas, montos) debe tener al menos un test.',
        ],
        'code_title': 'dbt_model.sql',
        'code_content': '-- Modelo incremental dbt para métricas diarias\n{{ config(\n    materialized="incremental",\n    unique_key="date_user",\n    partition_by={"field": "date", "data_type": "date"},\n    cluster_by=["user_id"]\n) }}\n\nWITH transactions AS (\n    SELECT * FROM {{ ref("stg_transactions") }}\n    {% if is_incremental() %}\n    WHERE date > (SELECT max(date) FROM {{ this }})\n    {% endif %}\n)\n\nSELECT\n    date,\n    user_id,\n    CONCAT(date, "-", user_id) AS date_user,\n    COUNT(*) AS transaction_count,\n    SUM(amount) AS total_amount,\n    AVG(amount) AS avg_amount\nFROM transactions\nGROUP BY date, user_id',
        'why': 'Incremental + unique_key evita duplicados. Partitioning + clustering reduce costos de BigQuery 100x. Tests garantizan integridad de datos.',
    },
    's38-performance-extreme': {
        'paragraphs': [
            'Numba es un compilador JIT (Just-In-Time) que convierte Python a código máquina via LLVM. Con `@numba.njit`, un loop numérico que tarda 500ms en Python puro corre en 5ms — 100x speedup. La limitación: Numba solo soporta tipos primitivos (int, float, arrays NumPy) y no soporta operaciones con strings, DataFrames, ni llamadas a APIs. Para funciones numéricas puras (cálculo de distancias, simulaciones Monte Carlo, procesamiento de señales), Numba es la herramienta #1. Usa `@njit(cache=True)` para cachear la compilación entre ejecuciones — el primer run compila (lento), los siguientes cargan del cache (instantáneo).',
            'Polars es la alternativa a pandas que usa Apache Arrow multi-threaded con evaluación lazy. En benchmarks reales, Polars es 5-30x más rápido que pandas en operaciones de groupby + join, y usa 2-5x menos memoria. La API es diferente: `pl.col("x").sum()` en vez de `df["x"].sum()`, y `df.group_by("col").agg(...)` en vez de `df.groupby("col").agg(...)`. La evaluación lazy (`df.lazy().filter(...).collect()`) optimiza el plan de ejecución: Polars puede reordenar operaciones, eliminar columnas no usadas, y paralelizar automáticamente. Para pipelines de datos con >1M filas, la migración de pandas a Polars es el upgrade de performance más impactante que puedes hacer.',
            'La vectorización con NumPy elimina loops de Python reemplazándolos con operaciones a nivel de array en C. En vez de `for i in range(n): result[i] = a[i] + b[i]`, escribes `result = a + b` — NumPy ejecuta todo en C sin overhead de Python. Para 1M de elementos, el loop tarda 500ms; la vectorización tarda 5ms. La regla: si tienes un for-loop sobre datos numéricos, hay una operación vectorizada de NumPy que lo reemplaza. `np.where()` reemplaza if/else, `np.vectorize()` reemplaza funciones custom, y broadcasting reemplaza loops anidados.',
        ],
        'code_title': 'numba_benchmark.py',
        'code_content': '"""Numba JIT vs Python puro: benchmark de distancias haversine."""\nimport numpy as np\nfrom numba import njit\nimport time\n\n@njit(cache=True, fastmath=True)\ndef haversine_numba(lat1, lon1, lat2, lon2):\n    """Distancia haversine optimizada con Numba JIT."""\n    R = 6371.0\n    dlat = np.radians(lat2 - lat1)\n    dlon = np.radians(lon2 - lon1)\n    a = (np.sin(dlat / 2) ** 2 + \n         np.cos(np.radians(lat1)) * np.cos(np.radians(lat2)) * \n         np.sin(dlon / 2) ** 2)\n    return 2 * R * np.arcsin(np.sqrt(a))\n\n# Generar 1M puntos\nn = 1_000_000\nlat1, lon1 = np.random.uniform(-12, -12.1, n), np.random.uniform(-77, -77.1, n)\nlat2, lon2 = np.random.uniform(-12, -12.1, n), np.random.uniform(-77, -77.1, n)\n\n# Benchmark\nstart = time.time()\ndistances = haversine_numba(lat1, lon1, lat2, lon2)\nprint(f"Numba: {time.time() - start:.4f}s para {n} puntos")\nprint(f"Distancia promedio: {distances.mean():.2f} km")',
        'why': '@njit(cache=True, fastmath=True) compila a LLVM IR con optimizaciones matemáticas. cache=True evita recompilar en runs siguientes. 100x speedup vs Python puro.',
    },
    's39-integrator-phase2': {
        'paragraphs': [
            'El proyecto integrador de Fase 2 consolida todas las skills Senior en un sistema end-to-end: ingesta de datos con Kafka, microservicio de inferencia con FastAPI + Docker + Kubernetes, modelo XGBoost con SHAP para interpretabilidad, y dashboard de monitoreo con Streamlit + Prometheus + Grafana. El objetivo es construir un sistema que cualquier startup peruana querría contratar para construir: un pipeline de scoring crediticio en tiempo real que procesa transacciones, calcula riesgo, y muestra resultados en un dashboard.',
            'La arquitectura del sistema tiene 5 componentes: (1) Kafka producer que envía eventos de transacciones, (2) FastAPI microservicio que consume eventos, extrae features del feature store, y llama al modelo XGBoost para scoring, (3) MLflow model registry para versionar y servir el modelo, (4) Prometheus + Grafana para monitorear latency, throughput, error rate, y model drift, (5) Streamlit dashboard para visualizar predicciones en tiempo real y alertas. Cada componente se despliega independientemente en Kubernetes con rolling updates zero-downtime.',
            'El CI/CD pipeline usa GitHub Actions: en cada push a main, se ejecutan tests con pytest (>85% cobertura), se construye la imagen Docker, se publica en GitHub Container Registry, y se despliega a Kubernetes con `kubectl apply`. El despliegue es canary: 10% del tráfico va a la nueva versión, 90% a la antigua. Si no hay errores en 30 minutos, el canary sube a 100%. Si hay errores, rollback automático. Este patrón es estándar en empresas US y es lo que diferencia a un Senior de un Mid-level.',
        ],
        'code_title': 'architecture.py',
        'code_content': '"""Arquitectura del sistema integrador Senior."""\n# Componentes del sistema:\n# 1. Kafka Producer -> topic "transactions"\n# 2. FastAPI Consumer -> scoring en tiempo real\n# 3. XGBoost Model -> MLflow registry\n# 4. Prometheus -> /metrics endpoint\n# 5. Streamlit Dashboard -> visualización\n\nfrom fastapi import FastAPI\nfrom prometheus_fastapi_instrumentator import Instrumentator\nimport xgboost as xgb\nimport mlflow\n\napp = FastAPI()\nInstrumentator().instrument(app).expose(app)\n\n# Cargar modelo desde MLflow\nmlflow.set_tracking_uri("http://mlflow:5000")\nmodel = mlflow.xgboost.load_model("models:/churn-xgb/Production")\n\n@app.post("/score")\nasync def score_transaction(transaction: dict):\n    """Scorea una transacción en tiempo real."""\n    features = extract_features(transaction)\n    prediction = model.predict_proba(features)[0, 1]\n    return {"risk_score": float(prediction), "risk_level": classify_risk(prediction)}',
        'why': 'La arquitectura integra 5 componentes que cubren todo el stack Senior: streaming, serving, ML, monitoring, y visualization. Cada componente es independiente y escalable.',
    },
    's42-graph-rag': {
        'paragraphs': [
            'GraphRAG combina knowledge graphs (Neo4j) con retrieval-augmented generation para dar respuestas más precisas que el RAG vector-only tradicional. En RAG vector-only, recuperas documentos similares al query por similitud coseno. En GraphRAG, también navegas las relaciones entre entidades: si el usuario pregunta "¿quiénes son los colegas de Ana?", el vector search encuentra documentos sobre Ana, pero el graph traversal encuentra explícitamente las relaciones "trabaja_con" conectadas a Ana. Esto es especialmente poderoso para preguntas multi-hop: "¿qué proyectos comparten los colegas de Ana?" — vector-only no puede responder esto porque requiere joins entre entidades.',
            'Neo4j es la base de datos de grafos más usada. Usa Cypher como query language: `MATCH (a:Person {name: "Ana"})-[:WORKS_WITH]->(b:Person) RETURN b.name`. En Python, la librería `neo4j` oficial conecta al driver. Para construir el knowledge graph, usas LLMs para extraer entidades (persona, empresa, proyecto) y relaciones (trabaja_con, pertenece_a) de documentos no estructurados. OpenAI structured outputs con pydantic garantiza que el LLM devuelva entidades y relaciones en formato válido. Luego, cargas estos en Neo4j con Cypher CREATE.',
            'El hybrid retrieval combina vector search (pgvector o Pinecone) con graph traversal (Neo4j). Primero, vector search encuentra los top-K documentos relevantes al query. Luego, graph traversal expande desde las entidades mencionadas en esos documentos, encontrando relaciones que el vector search no captura. Finalmente, combinas ambos contextos y los envías al LLM. En benchmarks RAGAS, GraphRAG reduce hallucination rate 40-60% vs vector-only RAG, especialmente en preguntas multi-hop y de razonamiento relacional.',
        ],
        'code_title': 'graphrag.py',
        'code_content': '"""GraphRAG: hybrid vector + graph retrieval."""\nfrom neo4j import GraphDatabase\nfrom openai import OpenAI\n\ndriver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "password"))\nclient = OpenAI()\n\ndef extract_entities(text: str) -> list[dict]:\n    """Extrae entidades y relaciones con LLM structured outputs."""\n    response = client.beta.chat.completions.parse(\n        model="gpt-4o",\n        response_format=EntityExtraction,\n        messages=[{"role": "user", "content": f"Extrae entidades de: {text}"}],\n    )\n    return response.choices[0].message.parsed.entities\n\ndef hybrid_retrieval(query: str) -> str:\n    """Retrieval híbrido: vector search + graph traversal."""\n    # 1. Vector search top-K documentos\n    docs = vector_store.similarity_search(query, k=5)\n    \n    # 2. Graph traversal desde entidades mencionadas\n    with driver.session() as session:\n        graph_context = session.run(\n            "MATCH (e:Entity)-[r]->(related) WHERE e.name IN $entities RETURN e, r, related",\n            entities=extract_entities(query),\n        )\n    \n    # 3. Combinar contexto para el LLM\n    context = f"Documentos: {docs}\\nRelaciones: {graph_context}"\n    return llm_generate(query, context)',
        'why': 'GraphRAG combina la precisión del vector search con el razonamiento relacional del graph traversal. Reduce hallucinations 40-60% en preguntas multi-hop.',
    },
    's43-llmops': {
        'paragraphs': [
            'LLMOps extiende DevOps/MLOps para sistemas basados en LLMs. Los desafíos únicos: (1) no hay "accuracy" tradicional — los LLMs generan texto, no clasificaciones, (2) el costo por request varía 100x según tokens, (3) los prompts son código que degrada con cambios de modelo. LangSmith (de LangChain) es la herramienta canónica de observabilidad: tracea cada step del pipeline (prompt, retrieval, generation, tool call) con latencia, tokens, y costo por step. Visualizas el razonamiento completo del modelo, lo que es imposible con un simple `print()`.',
            'RAGAS evalúa calidad de RAG con 4 métricas: (1) Faithfulness — la respuesta está fundamentada en el contexto recuperado (no hallucination), (2) Answer Relevancy — la respuesta responde la pregunta, (3) Context Precision — el contexto recuperado es relevante, (4) Context Recall — el contexto recuperado es completo. RAGAS usa un LLM como juez (GPT-4) para evaluar, lo que es costoso pero efectivo. La estrategia: corre RAGAS en un test set de 20-50 preguntas después de cada cambio de prompt, modelo, o chunking strategy. Si faithfulness baja de 0.85 a 0.70, hay un regression que debes investigar antes de deploy.',
            'El A/B testing de prompts es diferente al A/B testing tradicional porque no hay un solo metric (CTR, conversión). Mide: (1) calidad humana (human eval en escala 1-5), (2) costo por request (tokens × precio), (3) latencia, (4)满意度 del usuario (thumbs up/down). Usa feature flags (LaunchDarkly o custom) para enrutar 50% del tráfico a prompt A y 50% a prompt B. Después de 1000 interacciones por variante, aplica bootstrap confidence intervals para determinar si la diferencia es estadísticamente significativa. Promociona el ganador y depreca el perdedor.',
        ],
        'code_title': 'llmops_eval.py',
        'code_content': '"""LLMOps: tracing + evaluación con RAGAS."""\nfrom langsmith import traceable\nfrom ragas import evaluate\nfrom ragas.metrics import faithfulness, answer_relevancy\nfrom datasets import Dataset\n\n@traceable(name="rag_pipeline")\ndef rag_pipeline(question: str) -> str:\n    """Pipeline RAG con tracing automático en LangSmith."""\n    docs = retriever.get_relevant_documents(question)\n    context = "\\n".join([d.page_content for d in docs])\n    response = llm.invoke(f"Contexto: {context}\\nPregunta: {question}")\n    return response\n\n# Evaluar con RAGAS\ntest_data = Dataset.from_dict({\n    "question": ["¿Qué es Python?", "¿Cómo funciona Kafka?"],\n    "answer": [rag_pipeline(q) for q in questions],\n    "contexts": [[d.page_content for d in retriever.get_relevant_documents(q)] for q in questions],\n    "ground_truth": ["Python es un lenguaje...", "Kafka es un sistema..."],\n})\n\nresults = evaluate(test_data, metrics=[faithfulness, answer_relevancy])\nprint(f"Faithfulness: {results[\'faithfulness\']:.2f}")\nprint(f"Answer Relevancy: {results[\'answer_relevancy\']:.2f}")',
        'why': 'LangSmith tracea cada step del pipeline para debugging. RAGAS mide calidad objetivamente con 4 métricas. Correr en CI detecta regresiones antes de deploy.',
    },
    's44-multimodal': {
        'paragraphs': [
            'CLIP (Contrastive Language-Image Pre-training) de OpenAI alinea imágenes y texto en el mismo espacio vectorial. Esto permite buscar imágenes con texto (zero-shot image classification) y buscar texto con imágenes. En Python: `from transformers import CLIPModel; model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")`. Calculas embeddings de imagen y texto, y la similitud coseno indica qué tan relacionados están. Para un buscador de imágenes: pre-calculas embeddings de 1000 imágenes, luego para un query de texto, calculas el embedding del texto y encuentras las top-5 imágenes más similares por coseno.',
            'Whisper de OpenAI transcribe audio a texto con precisión cercana a humana en 99 idiomas. Para español, el modelo "base" es suficiente; para reuniones con ruido de fondo, usa "medium" o "large". En Python: `import whisper; model = whisper.load_model("base"); result = model.transcribe("audio.mp3")`. El resultado incluye timestamps por palabra, lo que permite subtítulos sincronizados. Whisper es la pieza clave para automatización de reuniones: transcribe → extrae action items con LLM → envía por email. Todo esto corre localmente con `faster-whisper` (CTranslate2) en una CPU normal.',
            'El multi-modal RAG indexa imágenes (via CLIP embeddings) y texto (via text embeddings) en el mismo vector store. Cuando el usuario hace un query, el retriever encuentra tanto documentos de texto como imágenes relevantes. El LLM (GPT-4V o LLaVA) puede entonces razonar sobre ambos: "Según el documento y el diagrama que encontré, el proceso es...". Esto es especialmente útil para manuales técnicos, reportes médicos, y análisis de diseños donde la información está distribuida entre texto e imágenes.',
        ],
        'code_title': 'clip_search.py',
        'code_content': '"""Buscador de imágenes con texto usando CLIP."""\nfrom transformers import CLIPModel, CLIPProcessor\nfrom PIL import Image\nimport torch\nimport numpy as np\n\nmodel = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")\nprocessor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")\n\ndef get_text_embedding(text: str) -> np.ndarray:\n    """Embedding de texto con CLIP."""\n    inputs = processor(text=text, return_tensors="pt", padding=True)\n    with torch.no_grad():\n        return model.get_text_features(**inputs).numpy()[0]\n\n# Buscar imágenes por texto\ntexts = ["un gato", "un perro", "un auto rojo"]\nimages = [Image.open(f"img{i}.jpg") for i in range(3)]\n\ninputs = processor(text=texts, images=images, return_tensors="pt", padding=True)\nwith torch.no_grad():\n    outputs = model(**inputs)\n    # Similitud coseno entre texto e imágenes\n    logits = outputs.logits_per_image\n    best_match = texts[logits[0].argmax()]\n    print(f"La imagen 0 es: {best_match}")',
        'why': 'CLIP permite zero-shot image classification sin entrenar un modelo custom. Solo necesitas describir las clases en texto y CLIP las clasifica.',
    },
    's45-iac': {
        'paragraphs': [
            'Terraform es el estándar de facto para Infraestructura como Código (IaC). Define recursos cloud en archivos .tf (declarativos), y Terraform se encarga de crear/modificar/eliminar los recursos para que el estado real coincida con el declarado. Para plataformas de IA, los recursos típicos son: instancias GPU (para entrenamiento), clusters Kubernetes (para serving), buckets S3/GCS (para datos y modelos), y bases de datos (para feature stores). La ventaja principal: reproducibilidad. Un `terraform apply` levanta toda la infra desde cero en minutos, y `terraform destroy` la elimina sin dejar recursos huérfanos que cobran.',
            'ArgoCD implementa GitOps: el estado deseado del cluster Kubernetes vive en un repo Git, y ArgoCD sincroniza continuamente el cluster con el repo. Cada git push a la rama main despliega automáticamente. La ventaja: el repo Git es la única fuente de verdad — no hay `kubectl apply` manual que pueda desincronizar el cluster. Si alguien hace un cambio manual en el cluster, ArgoCD lo revierte en el próximo sync. Para rollback, simplemente haces `git revert` y ArgoCD despliega la versión anterior automáticamente. Esto es lo que usan empresas como Intuit, BlackRock, y Tesla.',
            'FinOps es la práctica de optimizar costos cloud continuamente. Para IA, el costo #1 son las GPUs: una instancia NVIDIA T4 cuesta $0.90/hora en AWS, una A100 cuesta $3.00/hora. Para training, usa spot instances (60-70% de descuento) con checkpointing — si la instancia se interrumpe, reanudas desde el último checkpoint. Para inference, configura auto-scaling con KEDA: escala a 0 pods cuando no hay tráfico (ahorra 80% en workloads con tráfico variable). Usa Kubecost para visualizar costos por namespace, deployment, y pod. Sin FinOps, una plataforma de IA puede costar 3-5x más de lo necesario.',
        ],
        'code_title': 'main.tf',
        'code_content': '# Terraform: cluster Kubernetes con GPU nodes para ML\nterraform {\n  required_providers {\n    aws = { source = "hashicorp/aws", version = "~> 5.0" }\n  }\n}\n\nresource "aws_eks_cluster" "ml_cluster" {\n  name     = "ml-platform"\n  role_arn = aws_iam_role.eks_cluster.arn\n}\n\nresource "aws_eks_node_group" "gpu_nodes" {\n  cluster_name    = aws_eks_cluster.ml_cluster.name\n  node_group_name = "gpu-nodes"\n  node_role_arn   = aws_iam_role.eks_nodes.arn\n  \n  # GPU instance type\n  instance_types = ["g4dn.xlarge"]  # NVIDIA T4\n  \n  # Spot instances para ahorrar 60-70%\n  capacity_type  = "SPOT"\n  \n  scaling_config {\n    desired_size = 1\n    max_size     = 4  # Auto-scale hasta 4 GPUs\n    min_size     = 0  # Scale to zero cuando no hay tráfico\n  }\n}',
        'why': 'Terraform hace la infra reproducible. SPOT instances ahorran 60-70% en GPUs. min_size=0 permite scale-to-zero cuando no hay tráfico, ahorrando 80% en workloads variables.',
    },
    's46-gpu-computing': {
        'paragraphs': [
            'CuPy es el reemplazo drop-in de NumPy que corre en GPU. La API es idéntica: `import cupy as cp; a = cp.random.rand(5000, 5000); b = a @ a`. Para una matriz 5000×5000, NumPy en CPU tarda ~2 segundos; CuPy en GPU NVIDIA T4 tarda ~0.05 segundos — 40x speedup. La limitación: los datos deben caber en GPU memory (T4 tiene 16GB, A100 tiene 80GB). Si el dataset es más grande, necesitas chunking o multi-GPU. Para pipelines de ML que hacen cálculos numéricos intensivos (feature engineering, simulaciones, image processing), CuPy es el upgrade más fácil y impactante.',
            'PyTorch DDP (DistributedDataParallel) entrena modelos en múltiples GPUs. Cada GPU tiene una réplica completa del modelo y procesa un sub-batch diferente. Al final de cada step, las GPUs sincronizan gradients via NCCL (NVIDIA Collective Communications Library). Con 4 GPUs, obtienes ~3.5x speedup (no 4x por overhead de comunicación). La configuración: `torchrun --nproc_per_node=4 train.py` y en el código: `model = DDP(model, device_ids=[local_rank])`. DDP es simple pero requiere que el modelo quepa en una sola GPU. Para modelos muy grandes (LLMs), usa FSDP (Fully Sharded Data Parallel) que divide el modelo entre GPUs.',
            'vLLM es el servidor de inferencia más rápido para LLMs, 3-5x más rápido que HuggingFace transformers. La clave es PagedAttention: gestiona el KV cache como un sistema operativo gestiona memoria virtual, con pages que se asignan dinámicamente. Esto permite batchear 100+ requests concurrentes sin OOM. Para servir un modelo: `vllm serve mistralai/Mistral-7B-Instruct-v0.2 --tensor-parallel-size 2 --enable-chunked-prefill`. vLLM soporta streaming (SSE), OpenAI-compatible API, y quantización (AWQ, GPTQ). Para producción, vLLM + Kubernetes + auto-scaling es el stack estándar para servir LLMs en 2025-2026.',
        ],
        'code_title': 'cupy_benchmark.py',
        'code_content': '"""Benchmark CuPy (GPU) vs NumPy (CPU)."""\nimport numpy as np\nimport cupy as cp\nimport time\n\nn = 5000\n\n# NumPy en CPU\na_cpu = np.random.rand(n, n).astype(np.float32)\nstart = time.time()\nb_cpu = a_cpu @ a_cpu\nprint(f"NumPy CPU: {time.time() - start:.3f}s")\n\n# CuPy en GPU\na_gpu = cp.random.rand(n, n, dtype=cp.float32)\ncp.cuda.Stream.null.synchronize()  # Esperar transferencia\nstart = time.time()\nb_gpu = a_gpu @ a_gpu\ncp.cuda.Stream.null.synchronize()  # Esperar cómputo\nprint(f"CuPy GPU: {time.time() - start:.3f}s")\nprint(f"Speedup: {(time.time() - start):.1f}x")\n\n# Output típico:\n# NumPy CPU: 2.134s\n# CuPy GPU: 0.052s\n# Speedup: 41.0x',
        'why': 'CuPy tiene la misma API que NumPy pero corre en GPU. Para matrices grandes, el speedup es 40-100x. cp.cuda.Stream.null.synchronize() asegura que el cómputo terminó antes de medir.',
    },
    's47-opensource': {
        'paragraphs': [
            'Contribuir a Open Source es la forma más efectiva de construir reputación técnica internacional. En GitHub, los reclutadores buscan candidatos con PRs merged en proyectos conocidos (pandas, scikit-learn, FastAPI). Para empezar: busca issues con label "good first issue" en proyectos que ya usas. Un typo en la documentación, un bug en un edge case, o una mejora en un docstring son contribuciones válidas. El proceso: fork el repo, crea una rama, haz el cambio, escribe un test, abre un PR con descripción clara. La primera contribución merged es la más difícil — las siguientes son cada vez más fáciles.',
            'Diseñar una API pública para tu paquete Python requiere disciplina. La regla #1: todo lo que NO tiene underscore inicial es API pública y no puede cambiar sin un major version bump. Usa `__all__` en `__init__.py` para definir explícitamente qué se exporta. Sigue Semantic Versioning (semver): MAJOR.MINOR.PATCH. MAJOR para breaking changes, MINOR para nuevas features backward-compatible, PATCH para bugfixes. Antes de un breaking change, emite `DeprecationWarning` en la versión MINOR anterior. Usa `pyproject.toml` (PEP 621) con hatchling como build backend — es el estándar moderno que reemplaza a setup.py.',
            'El CI/CD para un paquete Open Source usa GitHub Actions con matrix testing: prueba en Python 3.10/3.11/3.12 × Ubuntu/macOS/Windows (9 combinaciones). El workflow: (1) lint con ruff, (2) tests con pytest + coverage, (3) build con hatch, (4) publish a Test PyPI en cada push a main, (5) publish a PyPI real en cada release. El archivo `.github/workflows/ci.yml` define todo esto. Sin CI matrix, tu paquete "funciona en mi máquina" pero falla en Windows o Python 3.10. Sin publish automático, olvidas publicar la nueva versión después de un merge.',
        ],
        'code_title': 'pyproject.toml',
        'code_content': '[build-system]\nrequires = ["hatchling"]\nbuild-backend = "hatchling.build"\n\n[project]\nname = "pytools-cli"\nversion = "1.0.0"\ndescription = "CLI toolkit profesional para Data Science"\nreadme = "README.md"\nrequires-python = ">=3.10"\nlicense = {text = "MIT"}\ndependencies = [\n    "click>=8.0",\n    "pandas>=2.0",\n    "rich>=13.0",\n]\n\n[project.optional-dependencies]\ndev = ["pytest", "ruff", "mypy"]\n\n[project.scripts]\npytools = "pytools_cli.main:cli"\n\n[tool.ruff]\nline-length = 100\ntarget-version = "py310"',
        'why': 'pyproject.toml con hatchling es el estándar moderno (PEP 621). project.scripts crea el comando ejecutable. optional-dependencies separa deps de dev. ruff reemplaza flake8 + black + isort en una sola herramienta.',
    },
    's48-ai-governance': {
        'paragraphs': [
            'La gobernanza de IA abarca bias detection, fairness, transparencia, y compliance. En Python, fairlearn de Microsoft mide fairness con métricas como demographic parity (la predicción es independiente del grupo demográfico) y equalized odds (el modelo tiene el mismo FPR y TPR en todos los grupos). Un disparate impact ratio < 0.8 indica bias: el modelo aprueba créditos al 40% de mujeres pero al 60% de hombres, ratio = 40/60 = 0.67 < 0.8 → hay bias. La mitigación incluye reweighting (dar más peso a muestras del grupo desaventajado) o post-processing (ajustar el threshold por grupo).',
            'EU AI Act (en vigor desde febrero 2025) clasifica sistemas de IA en 4 niveles de riesgo: unacceptable (prohibido), high (regulación estricta), limited (transparencia), minimal (sin regulación). Los sistemas de scoring crediticio, contratación, y justicia son "high risk" y requieren: evaluación de impacto, documentación técnica, logging, human oversight, y conformidad con estándares de calidad. Las empresas peruanas que sirven clientes europeos deben cumplir. Un model card (documentación del modelo) es el primer paso: describe intended use, training data, métricas, limitaciones, y consideraciones éticas.',
            'La auditoría de sistemas de IA es un proceso continuo, no un evento único. Checklist trimestral: (1) ¿El modelo sigue siendo preciso o hay drift? (2) ¿Los datos de entrada siguen teniendo la misma distribución? (3) ¿Hay nuevos sesgos detectados? (4) ¿Las regulaciones cambiaron? (5) ¿Hay parches de seguridad pendientes? Automatiza lo que puedas con pytest + custom assertions: `assert fairness_ratio > 0.8`, `assert accuracy > 0.85`, `assert no_pii_in_logs`. Cuando un assert falla, el pipeline se detiene y notifica al equipo. Sin auditoría continua, tu modelo de IA se degrada silenciosamente hasta que alguien nota que las predicciones son incorrectas — para entonces, el daño ya está hecho.',
        ],
        'code_title': 'bias_check.py',
        'code_content': '"""Detección de bias con fairlearn."""\nfrom fairlearn.metrics import MetricFrame, demographic_parity_difference\nfrom sklearn.metrics import accuracy_score\nimport numpy as np\n\n# Predicciones y datos sensibles\ny_true = np.array([1, 0, 1, 0, 1, 0, 1, 0])\ny_pred = np.array([1, 0, 1, 0, 0, 0, 1, 0])  # Modelo\nsensitive = np.array(["M", "M", "M", "M", "F", "F", "F", "F"])  # Género\n\n# Medir fairness por grupo\nmetric_frame = MetricFrame(\n    metrics=accuracy_score,\n    y_true=y_true,\n    y_pred=y_pred,\n    sensitive_features=sensitive,\n)\n\nprint(f"Accuracy por grupo: {metric_frame.by_group.to_dict()}")\nprint(f"Accuracy M: {metric_frame.by_group[\'M\']:.2f}")\nprint(f"Accuracy F: {metric_frame.by_group[\'F\']:.2f}")\n\n# Disparate impact ratio\ndpd = demographic_parity_difference(y_true, y_pred, \n                                     sensitive_features=sensitive)\nprint(f"Disparate impact difference: {dpd:.3f}")\nif abs(dpd) > 0.1:\n    print("⚠️ Bias detectado - revisar modelo")',
        'why': 'fairlearn mide bias objetivamente. Un disparate impact > 0.1 indica sesgo significativo. La auditoría debe ser continua, no un evento único.',
    },
    's49-data-contracts': {
        'paragraphs': [
            'Un data contract es un acuerdo formal entre quien produce datos y quien los consume. Define: schema (columnas, tipos), quality rules (no nulls, rangos válidos), SLAs (frescura máxima), y ownership (quién responde cuando algo falla). Sin data contracts, el productor puede cambiar una columna de int a float sin avisar, y el pipeline del consumidor se rompe en producción a las 3am. Con data contracts, el cambio requiere una nueva versión del contrato (backward compatible o con migración planificada). En Python, pydantic define el schema: `class Transaction(BaseModel): id: str; amount: PositiveFloat; date: datetime`.',
            'Great Expectations valida data contracts en cada paso del pipeline. Defines Expectation Suites: `expect_column_to_not_be_null("user_id")`, `expect_column_values_to_be_unique("transaction_id")`, `expect_column_values_to_be_between("amount", min_value=0, max_value=100000)`. Si una expectation falla, el pipeline se detiene con error y notifica al owner. Esto previene que datos corruptos propaguen a dashboards y modelos de ML. La integración con dbt es directa: dbt tests son una forma lightweight de data contracts, y Great Expectations es la versión heavy-duty para pipelines críticos.',
            'OpenLineage captura metadata de cada paso del pipeline automáticamente: qué dataset se leyó, qué transformación se aplicó, qué dataset se escribió, quién lo ejecutó, cuándo. Esto construye un grafo de linaje que responde: "si la tabla `user_features` tiene un bug, ¿qué dashboards y modelos de ML se ven afectados?" Sin linaje, investigar el impacto de un cambio de datos es manual y propenso a errores. OpenLineage se integra con Prefect, Airflow, dbt, y Spark — cada herramienta reporta su lineage automáticamente a un backend (Marquez o DataHub) donde se visualiza como un DAG.',
        ],
        'code_title': 'data_contract.py',
        'code_content': '"""Data contract con pydantic + Great Expectations."""\nfrom pydantic import BaseModel, PositiveFloat, Field\nfrom datetime import datetime\nimport great_expectations as gx\n\nclass TransactionContract(BaseModel):\n    """Data contract para transacciones."""\n    transaction_id: str = Field(..., min_length=1)\n    user_id: str = Field(..., min_length=1)\n    amount: PositiveFloat = Field(..., le=100000)\n    timestamp: datetime\n    currency: str = Field(..., pattern="^(PEN|USD|EUR)$")\n\n# Validar con pydantic\ntx = TransactionContract(\n    transaction_id="tx_001",\n    user_id="user_123",\n    amount=150.50,\n    timestamp=datetime.now(),\n    currency="PEN",\n)\nprint(f"Contrato válido: {tx.transaction_id}")\n\n# Validar DataFrame con Great Expectations\ncontext = gx.get_context()\nbatch = context.get_batch({"datasource": "transactions", "table": "raw"})\nbatch.expect_column_to_not_be_null("transaction_id")\nbatch.expect_column_values_to_be_unique("transaction_id")\nbatch.expect_column_values_to_be_between("amount", 0, 100000)\nresults = batch.validate()\nprint(f"Validación: {\'PASS\' if results.success else \'FAIL\'}")',
        'why': 'pydantic valida schema en runtime. Great Expectations valida quality rules en el pipeline. Sin data contracts, un cambio de schema del productor rompe al consumidor en producción.',
    },
    's50-tech-leadership': {
        'paragraphs': [
            'Un design doc es un documento de 2-5 páginas que describe una feature compleja antes de implementarla. Estructura: (1) Context — qué problema resuelves y por qué importa, (2) Goals — qué vas a lograr específicamente, (3) Design — cómo lo vas a hacer (con diagramas), (4) Alternatives — qué otras opciones consideraste y por qué las descartaste, (5) Risks — qué puede salir mal. El design doc se comparte con stakeholders para feedback ANTES de escribir código. Esto evita que pases 2 semanas implementando algo que el equipo no quiere. En empresas serias, ningún feature complejo se implementa sin un design doc aprobado.',
            'Un postmortem blameless documenta un incidente de producción sin culpar a personas. Estructura: (1) Summary — qué pasó en 2 líneas, (2) Timeline — cronología de eventos con timestamps, (3) Root Cause — por qué pasó (usa "5 whys"), (4) Impact — cuántos usuarios/dinero/time se perdió, (5) Action Items — qué vamos a hacer para que no vuelva a pasar (con owners y deadlines). La cultura blameless es clave: si la gente tiene miedo de ser culpada, ocultan errores. Si se analiza el error sin culpa, el equipo aprende y mejora. "El engineer hizo X" → "El proceso permitió que X pasara sin ser detectado".',
            'La entrevista de system design evalúa si un candidato puede diseñar sistemas a escala. Formato: 45 minutos, pregunta abierta como "diseña un sistema de scoring crediticio en tiempo real". El candidato debe: (1) clarificar requisitos (¿cuántos QPS? ¿latencia máxima? ¿consistencia?), (2) proponer arquitectura (componentes, APIs, data flow), (3) discutir trade-offs (¿SQL vs NoSQL? ¿sync vs async? ¿batch vs streaming?), (4) identificar bottlenecks (¿DB? ¿cache? ¿compute?), (5) planear monitoreo (métricas, alertas, SLOs). Como entrevistador, evalúa: claridad de pensamiento, conocimiento de trade-offs, comunicación, y escalabilidad del diseño.',
        ],
        'code_title': 'design_doc.md',
        'code_content': '# Design Doc: Sistema de Scoring Crediticio en Tiempo Real\n\n## Context\nEl equipo de riesgo necesita un sistema que scoree transacciones\nde crédito en <100ms para aprobar/rechazar en tiempo real.\n\n## Goals\n- Latencia p99 < 100ms por request\n- Throughput: 10,000 requests/segundo\n- Disponibilidad: 99.9% uptime\n- Interpretabilidad: SHAP values por predicción\n\n## Design\n- API: FastAPI + uvicorn (async)\n- Modelo: XGBoost servido con MLflow\n- Cache: Redis para features pre-calculadas\n- Queue: Kafka para eventos asíncronos\n- Monitoring: Prometheus + Grafana\n\n## Alternatives\n- Batch scoring: descartado (necesitan tiempo real)\n- Lambda function: descartado (cold start > 100ms)\n- gRPC en vez de REST: descartado (clientes usan REST)\n\n## Risks\n- Feature drift: mitigar con Evidently monitoring\n- Modelo degradation: re-entrenar mensualmente\n- Redis OOM: configurar eviction policy LRU',
        'why': 'Un design doc alinea stakeholders antes de implementar. Documentar alternatives y risks previene "¿por qué no usamos X?" meses después. El formato es conciso (2-5 páginas) pero completo.',
    },
    's51-integrator-final': {
        'paragraphs': [
            'El proyecto integrador final consolida todo el curso en una plataforma agéntica de IA production-grade. La plataforma combina: (1) LangGraph multi-agent con 3 sub-agentes (researcher con RAG, analyst con datos, writer de reportes), (2) modelo fine-tuned con QLoRA para dominio específico, (3) RAG con knowledge graph para razonamiento relacional, (4) LLMOps completo con LangSmith tracing, RAGAS evaluation, y A/B testing, (5) despliegue con Terraform + Kubernetes + ArgoCD. El objetivo: construir un sistema que un startup peruano podría usar como producto, no un toy project.',
            'QLoRA (Quantized Low-Rank Adaptation) fine-tunea un LLM en una GPU consumer. Cuantiza el modelo base a 4-bit (NF4) y solo entrena adapters LoRA (0.1% de los parámetros). Un Llama 3.1 8B se fine-tunea en una RTX 3090 (24GB) en 3 horas con 1000 ejemplos. El resultado: un modelo especializado en tu dominio (ej. análisis de facturas peruanas, soporte al cliente en español) que supera a GPT-4 en tareas específicas, pero corre localmente sin costo por token. La integración con Ollama permite servir el modelo fine-tuned en producción con la misma API que un modelo base.',
            'El despliegue usa Terraform para provisionar el cluster Kubernetes con GPU nodes, ArgoCD para GitOps, y Prometheus + Grafana para monitoring. El pipeline CI/CD: (1) push a main → tests, (2) build Docker image, (3) deploy canary 10%, (4) si sin errores en 30min → 100%, (5) si errores → rollback automático. La plataforma se monitorea con LangSmith (LLM tracing), RAGAS (calidad del RAG), y Prometheus (latency, throughput, error rate). Un dashboard de Grafana une todo en una vista ejecutiva: "plataforma saludable, 99.9% uptime, AUC del modelo 0.87, costo $50/día".',
        ],
        'code_title': 'qlora_finetune.py',
        'code_content': '"""Fine-tuning con QLoRA para dominio específico."""\nfrom transformers import AutoModelForCausalLM, TrainingArguments\nfrom peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training\nfrom transformers import BitsAndBytesConfig\nimport torch\n\n# Configuración QLoRA: 4-bit quantization\nbnb_config = BitsAndBytesConfig(\n    load_in_4bit=True,\n    bnb_4bit_quant_type="nf4",\n    bnb_4bit_compute_dtype=torch.float16,\n    bnb_4bit_use_double_quant=True,\n)\n\n# Cargar modelo base cuantizado\nmodel = AutoModelForCausalLM.from_pretrained(\n    "meta-llama/Llama-3.1-8B",\n    quantization_config=bnb_config,\n    device_map="auto",\n)\nmodel = prepare_model_for_kbit_training(model)\n\n# Configurar LoRA adapters (solo 0.1% de parámetros)\nlora_config = LoraConfig(\n    r=16,  # Rank del adapter\n    lora_alpha=32,\n    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],\n    lora_dropout=0.05,\n    task_type="CAUSAL_LM",\n)\nmodel = get_peft_model(model, lora_config)\nprint(f"Parámetros entrenables: {model.print_trainable_parameters()}")\n# Salida: trainable: 8M (0.1%) | total: 8B (100%)',
        'why': 'QLoRA permite fine-tunear un modelo de 8B parámetros en una GPU consumer de 24GB. Solo entrena 0.1% de parámetros (adapters LoRA), pero el resultado supera al modelo base en tareas de dominio específico.',
    },
    's52-career-strategy': {
        'paragraphs': [
            'Un portfolio site es tu CV interactivo. Debe mostrar 3 proyectos con demo en vivo (no solo código en GitHub), case study escrito (problema, solución, impacto), y stack técnico. Usa Next.js + Tailwind para un diseño profesional. Deploya en Vercel (gratis). Incluye: nombre, título, bio de 2 líneas, 3 proyectos con screenshots/demo, links a GitHub y LinkedIn, y un formulario de contacto. Sin portfolio site, eres uno más entre 1000 CVs. Con uno, demuestras que puedes construir cosas reales, no solo pasar entrevistas.',
            'Un CV técnico optimizado para ATS (Applicant Tracking Systems) tiene 70% de keyword overlap con el job description. ATS filtra CVs automáticamente antes de que un humano los vea. Si la oferta dice "Python, pandas, scikit-learn, AWS, Docker, Kubernetes", tu CV debe incluir esas palabras exactas. Formato: 1 página, sin tablas ni imágenes (ATS no las lee bien), logros cuantificables ("Reduje latencia 80% optimizando con ONNX, sirviendo 10M predicciones/día"), no responsabilidades ("Desarrollé pipelines de ML"). Usa verbos de acción: construí, optimicé, lideré, automaticé. Cada bullet point debe tener un número.',
            'El networking en conferencias es la forma más efectiva de conseguir entrevistas sin aplicar. Prepara un pitch de 2 minutos: quién soy, qué hago, qué busco, qué me hace único. Asiste a PyCon, DataDay, Latin America AI Summit, y meetups locales. Después de cada charla, acércate al speaker y haz una pregunta específica. Intercambia LinkedIn (no WhatsApp — más profesional). Después del evento, envía un mensaje: "Hola X, fue un gusto escuchar tu charla sobre Y en PyCon. Estoy trabajando en algo similar y me encantaría conversar". El 80% no responde, pero el 20% que sí puede cambiar tu carrera.',
        ],
        'code_title': 'cv_tips.md',
        'code_content': '# CV Técnico - Tips ATS\n\n## Formato\n- 1 página máximo\n- Sin tablas, sin imágenes, sin columnas\n- Fuente: Arial o Calibri 11pt\n- Formato: PDF (no Word)\n\n## Estructura\n1. Header: Nombre | Título | Email | LinkedIn | GitHub\n2. Summary: 2 líneas con tu propuesta de valor\n3. Experience: 3-4 logros cuantificables por rol\n4. Skills: Python, pandas, scikit-learn, AWS, Docker, K8s\n5. Education: Universidad | Título | Año\n6. Certifications: AWS MLA-C01, GCP PMLE\n\n## Logros cuantificables (ejemplos)\n❌ "Desarrollé pipelines de ML"\n✅ "Construí pipeline de churn prediction con XGBoost,\n    reduciendo churn 15% y salvando S/2M anuales"\n\n❌ "Trabajé con datos"\n✅ "Procesé 50M transacciones diarias con Kafka + Spark,\n    reduciendo latencia 80% vs solución anterior"\n\n❌ "Usé Python"\n✅ "Automaticé 200h/mes de trabajo manual con Python + Playwright,\n    deployando en GitHub Actions con 99.5% uptime"',
        'why': 'Un CV ATS-friendly con logros cuantificables tiene 3x más probabilidad de pasar el filtro automático. Los números demuestran impacto de negocio, no solo habilidades técnicas.',
    },
}

def escape_sq(s):
    """Escape for TypeScript single-quote string."""
    if not s:
        return ''
    return s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")

count = 0
for slug, data in SECTIONS.items():
    filepath = f"src/lib/course/sections/{slug}.ts"
    if not os.path.exists(filepath):
        print(f"  ✗ {slug} not found")
        continue

    with open(filepath, 'r') as f:
        content = f.read()

    # Replace generic paragraphs
    old_paras = """        'En esta lección vamos a explorar Fundamentos en profundidad. Este concepto es fundamental para tu crecimiento como profesional de Data Science y automatización. En el mercado laboral peruano e internacional, dominar este tema te diferencia claramente de otros candidatos.',

        'La clave para entender Fundamentos es practicar con ejemplos reales. No basta con leer la teoría — necesitas escribir código, cometer errores, y aprender de ellos. Por eso cada concepto viene acompañado de ejemplos prácticos que puedes ejecutar en el editor interactivo.',

        'En producción, Fundamentos se usa diario en empresas como Interbank, BBVA, Mercado Libre y Rimac. Los equipos de data science y automatización dependen de este conocimiento para construir pipelines robustos y escalables.',"""

    new_paras = "\n".join([f"        '{escape_sq(p)}'," for p in data['paragraphs']])

    if old_paras in content:
        content = content.replace(old_paras, new_paras)
    else:
        # Try to find and replace the paragraphs block
        import re
        pattern = r"      paragraphs: \[\n.*?\n      \],"
        replacement = f"      paragraphs: [\n{new_paras}\n      ],"
        content = re.sub(pattern, replacement, content, count=1, flags=re.DOTALL)

    # Replace generic code
    old_code = "# Ejemplo de: Demostración del concepto principal\\n# TODO: Implementar el código completo\\nprint(\"Implementar este ejemplo\")"
    new_code = data['code_content'].replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")

    if old_code in content:
        content = content.replace(old_code, new_code)

    # Replace generic why
    old_why = "Este paso es importante porque demuestra el concepto en acción y te muestra el patrón correcto a seguir."
    new_why = data['why']
    if old_why in content:
        content = content.replace(old_why, new_why)

    with open(filepath, 'w') as f:
        f.write(content)
    count += 1
    print(f"  ✓ {slug}: theory + code + why updated")

print(f"\n✓ {count} sections expanded with real content")
