// Static image imports (`import shot from './x.png'`) are typed by Next's own declarations, which
// next-env.d.ts pulls in. That file is generated by `next dev`/`next build` and gitignored, so a
// bare `npx tsc --noEmit` on a fresh checkout would not see them. Sesión 0's screenshots
// (src/assets/setup/index.ts) are the first such imports in src/.
/// <reference types="next/image-types/global" />
