/** Auto-generated glossary SSOT — source of hover hints + Glossary dialog */
export type GlossaryCategory = 'Python' | 'Data Science' | 'NumPy' | 'Pandas' | 'ML' | 'Tooling'

export interface GlossaryTerm {
  id: string
  term: string
  aliases: string[]
  category: GlossaryCategory
  definition: string
  definitionEn?: string
  example?: string
  related?: string[]
  /** Section id where term is first introduced (curriculum order) */
  firstSectionId: string
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    id: 'variable',
    term: 'Variable',
    aliases: ["Variable"],
    category: 'Python',
    definition: 'Una etiqueta que apunta a un valor en memoria. En Python no declaras el tipo — se infiere.',
    example: 'x = 42\\nnombre = "Ana"',
    related: ["Tipo de dato", "Asignación"],
    firstSectionId: 'setup',
  },
  {
    id: 'tipo-de-dato',
    term: 'Tipo de dato',
    aliases: ['Tipo de dato', 'tipos de datos'],
    category: 'Python',
    definition: 'La naturaleza del valor: int (entero), float (decimal), str (texto), bool (True/False), list, dict, tuple, set.',
    firstSectionId: 'basics',
  },
  {
    id: 'list-comprehension',
    term: 'List comprehension',
    aliases: ["List comprehension"],
    category: 'Python',
    definition: 'Sintaxis compacta para crear listas a partir de otras. Más rápido y pythónico que un loop for.',
    example: '[x**2 for x in range(5) if x > 0]  # [1, 4, 9, 16]',
    firstSectionId: 'basics',
  },
  {
    id: 'dict-comprehension',
    term: 'Dict comprehension',
    aliases: ["Dict comprehension"],
    category: 'Python',
    definition: 'Similar a list comprehension pero crea diccionarios.',
    example: '{k: v**2 for k, v in {"a": 1, "b": 2}.items()}',
    firstSectionId: 'data-structures',
  },
  {
    id: 'f-string',
    term: 'f-string',
    aliases: ["f-string"],
    category: 'Python',
    definition: 'String formatting con f prefijo. Permite insertar variables directamente con {}.',
    example: 'f"Hola {nombre}, tienes {edad} años"',
    firstSectionId: 'basics',
  },
  {
    id: 'slicing',
    term: 'Slicing',
    aliases: ['Slicing', 'slice'],
    category: 'Python',
    definition: 'Extraer una porción de una secuencia. Sintaxis: secuencia[inicio:fin:paso].',
    example: 'lista[1:4]  # elementos del índice 1 al 3\\nlista[::-1]  # reverso',
    firstSectionId: 'data-structures',
  },
  {
    id: 'truthiness',
    term: 'Truthiness',
    aliases: ['Truthiness', 'truthy', 'falsy'],
    category: 'Python',
    definition: 'Valores que se evalúan como False: 0, 0.0, "", [], {}, None. Todo lo demás es True.',
    firstSectionId: 'basics',
  },
  {
    id: 'dunder-method',
    term: 'Dunder method',
    aliases: ['Dunder method', 'dunder', '__init__'],
    category: 'Python',
    definition: 'Métodos especiales con __ al inicio y fin (double underscore). Ej: __init__, __str__, __repr__, __len__.',
    firstSectionId: 'oop',
  },
  {
    id: 'decorador',
    term: 'Decorador',
    aliases: ['Decorador', 'decorator', 'decorators'],
    category: 'Python',
    definition: 'Función que recibe otra función y devuelve una nueva con comportamiento extendido. Se aplica con @.',
    example: '@timing\\ndef mi_func(): ...',
    firstSectionId: 'functions-modules',
  },
  {
    id: 'generator',
    term: 'Generator',
    aliases: ['Generator', 'generador', 'yield'],
    category: 'Python',
    definition: 'Función que usa yield para producir valores uno a uno, sin cargar todo en memoria.',
    example: 'def cuenta():\\n    for i in range(10):\\n        yield i',
    firstSectionId: 'functions-modules',
  },
  {
    id: 'context-manager',
    term: 'Context manager',
    aliases: ['Context manager', 'contextlib'],
    category: 'Python',
    definition: 'Objeto que define setup (__enter__) y cleanup (__exit__). Se usa con el statement with.',
    example: 'with open("f.csv") as f:\\n    data = f.read()',
    firstSectionId: 'functions-modules',
  },
  {
    id: 'abc',
    term: 'ABC',
    aliases: ["ABC"],
    category: 'Python',
    definition: 'Abstract Base Class. Define interfaces: métodos que las subclases DEBEN implementar. No se puede instanciar directamente.',
    firstSectionId: 'setup',
  },
  {
    id: 'args-y-kwargs',
    term: 'args y kwargs',
    aliases: ['args y kwargs', 'kwargs', '**kwargs', '*args'],
    category: 'Python',
    definition: '*args junta argumentos posicionales en tupla. **kwargs junta argumentos keyword en dict.',
    firstSectionId: 'functions-modules',
  },
  {
    id: 'virtual-environment-venv',
    term: 'Entorno virtual (venv)',
    aliases: [
      'Entorno virtual (venv)',
      'entorno virtual',
      'entornos virtuales',
      'Virtual environment (venv)',
      'Virtual environment',
      'venv',
      '.venv',
    ],
    category: 'Tooling',
    definition:
      'Carpeta aislada del proyecto (canónica: .venv) con su propio Python y paquetes. Evita que las dependencias de un cliente rompan otro proyecto.',
    firstSectionId: 'setup',
  },
  {
    id: 'repositorio-repo',
    term: 'Repositorio (repo)',
    aliases: ['Repositorio (repo)', 'repositorio', 'repo', 'repository', 'repos'],
    category: 'Tooling',
    definition:
      'Carpeta del proyecto bajo control de versiones Git: guarda el código y el historial de cambios. En la jerga se abrevia «repo».',
    firstSectionId: 'setup',
  },
  {
    id: 'git',
    term: 'Git',
    aliases: ['Git', 'git'],
    category: 'Tooling',
    definition:
      'Sistema de control de versiones: registra quién cambió qué archivo y por qué (commits), en tu máquina y al sincronizar con remotos.',
    firstSectionId: 'setup',
  },
  {
    id: 'github',
    term: 'GitHub',
    aliases: ['GitHub', 'github'],
    category: 'Tooling',
    definition:
      'Servicio en la nube (remoto) donde publicas repos Git, abres Pull Requests y colaboras con el equipo. No es lo mismo que Git (Git es el sistema; GitHub es un hosting).',
    firstSectionId: 'setup',
  },
  {
    id: 'clonar',
    term: 'Clonar',
    aliases: ['Clonar', 'clonar', 'clone', 'clonación'],
    category: 'Tooling',
    definition:
      'Copiar un repositorio desde un remoto (p. ej. GitHub) a tu laptop con `git clone`, incluyendo el historial.',
    firstSectionId: 'setup',
  },
  {
    id: 'commit',
    term: 'Commit',
    aliases: ['Commit', 'commit', 'commits'],
    category: 'Tooling',
    definition:
      'Snapshot del historial Git con un mensaje: guarda un punto de retorno de tus cambios (`git commit -m "..."`).',
    firstSectionId: 'setup',
  },
  {
    id: 'pull-request',
    term: 'Pull Request (PR)',
    aliases: ['Pull Request (PR)', 'Pull Request', 'pull request', 'PR'],
    category: 'Tooling',
    definition:
      'Propuesta de cambios en un remoto (GitHub/GitLab) para que revisen e integren tu rama a main (u otra rama base).',
    firstSectionId: 'setup',
  },
  {
    id: 'path',
    term: 'PATH',
    aliases: ['PATH', 'Path'],
    category: 'Tooling',
    definition:
      'Lista de carpetas donde el sistema operativo busca programas cuando escribes un comando (p. ej. `python`). Si Python no está en el PATH, la terminal «no lo reconoce».',
    firstSectionId: 'setup',
  },
  {
    id: 'interprete',
    term: 'Intérprete',
    aliases: ['Intérprete', 'intérprete', 'interprete', 'interpreter'],
    category: 'Python',
    definition:
      'El programa Python que lee y ejecuta tu código (`python` / `python3`). Verificar la versión y la ruta evita instalar paquetes en un Python y ejecutar otro.',
    firstSectionId: 'setup',
  },
  {
    id: 'repl',
    term: 'REPL',
    aliases: ['REPL', 'repl'],
    category: 'Python',
    definition:
      'Read–Eval–Print Loop: modo interactivo del intérprete (prompt `>>>`) para probar expresiones sin crear un archivo `.py`.',
    firstSectionId: 'setup',
  },
  {
    id: 'pip',
    term: 'pip',
    aliases: ['pip', 'Pip'],
    category: 'Tooling',
    definition:
      'Instalador de paquetes de terceros desde PyPI. Úsalo como `python -m pip` para atarlo al mismo intérprete del entorno virtual.',
    firstSectionId: 'setup',
  },
  {
    id: 'requirements-txt',
    term: 'requirements.txt',
    aliases: ['requirements.txt', 'requirements'],
    category: 'Tooling',
    definition:
      'Archivo de texto que lista dependencias del proyecto (a menudo con versión pinneada). Se restaura con `pip install -r requirements.txt`.',
    firstSectionId: 'setup',
  },
  {
    id: 'dependencias',
    term: 'Dependencias',
    aliases: ['Dependencias', 'dependencias', 'dependency', 'dependencies'],
    category: 'Tooling',
    definition:
      'Paquetes o librerías que tu proyecto necesita para correr (pandas, numpy, etc.). En Python de terceros se instalan con pip en el venv.',
    firstSectionId: 'setup',
  },
  {
    id: 'conventional-commits',
    term: 'Conventional Commits',
    aliases: ['Conventional Commits', 'conventional commits'],
    category: 'Tooling',
    definition:
      'Estándar para mensajes de commit: prefijos feat:, fix:, docs:, refactor:, test:, chore: + descripción clara en imperativo.',
    firstSectionId: 'setup',
  },
  {
    id: 'terminal-shell',
    term: 'Terminal (shell)',
    aliases: ['Terminal (shell)', 'terminal', 'Terminal', 'shell', 'Shell', 'línea de comandos'],
    category: 'Tooling',
    definition:
      'Ventana de texto donde escribes comandos al sistema (PowerShell, bash, zsh). Ahí corres `python`, `git` y activas el venv.',
    firstSectionId: 'setup',
  },
  {
    id: 'dotenv',
    term: '.env',
    aliases: ['.env', 'env file', 'archivo .env'],
    category: 'Tooling',
    definition:
      'Archivo local de variables y secretos (API keys, contraseñas). Nunca se sube al repo; usa `.env.example` solo con nombres de claves.',
    firstSectionId: 'setup',
  },
  {
    id: 'gitignore',
    term: '.gitignore',
    aliases: ['.gitignore', 'gitignore'],
    category: 'Tooling',
    definition:
      'Archivo que le dice a Git qué no trackear (p. ej. `.venv/`, `__pycache__/`, `.env`). Si un archivo ya está trackeado, hay que sacarlo del índice aparte.',
    firstSectionId: 'setup',
  },
  {
    id: 'ruff',
    term: 'Ruff',
    aliases: ['Ruff', 'ruff'],
    category: 'Tooling',
    definition:
      'Linter y formateador de Python muy rápido. En S01 se usa `ruff check` para atrapar errores baratos antes del code review.',
    firstSectionId: 'setup',
  },
  {
    id: 'vs-code',
    term: 'VS Code',
    aliases: ['VS Code', 'vscode', 'Visual Studio Code', 'Vs Code'],
    category: 'Tooling',
    definition:
      'Editor de código gratuito de Microsoft. Con la extensión Python (Pylance) y Ruff es el entorno recomendado de este curso.',
    firstSectionId: 'setup',
  },
  {
    id: 'notebook',
    term: 'Notebook',
    aliases: ['Notebook', 'notebook', 'Jupyter', 'jupyter', 'ipynb'],
    category: 'Tooling',
    definition:
      'Documento interactivo (a menudo Jupyter `.ipynb`) que mezcla celdas de código y texto. Útil para exploración; el código de producción suele vivir en scripts `.py`.',
    firstSectionId: 'setup',
  },
  {
    id: 'pytest',
    term: 'pytest',
    aliases: ["pytest"],
    category: 'Tooling',
    definition: 'Framework de testing para Python. Más simple que unittest. Descubre automáticamente test_*.py.',
    firstSectionId: 'basics',
  },
  {
    id: 'coverage',
    term: 'Coverage',
    aliases: ['Coverage', 'cobertura'],
    category: 'Tooling',
    definition: 'Porcentaje de líneas de código cubiertas por tests. pytest --cov=mi_modulo.',
    firstSectionId: 'testing',
  },
  {
    id: 'list',
    term: 'List',
    aliases: ["List"],
    category: 'Python',
    definition: 'Secuencia ordenada mutable. [1, 2, 3]. Métodos: append, extend, insert, remove, sort.',
    firstSectionId: 'setup',
  },
  {
    id: 'dict',
    term: 'Dict',
    aliases: ["Dict"],
    category: 'Python',
    definition: 'Pares clave-valor con búsqueda O(1). {"nombre": "Ana", "edad": 25}. Métodos: get, items, keys, values.',
    firstSectionId: 'setup',
  },
  {
    id: 'tuple',
    term: 'Tuple',
    aliases: ["Tuple"],
    category: 'Python',
    definition: 'Lista inmutable. (1, 2, 3). Más rápida y segura para datos que no cambian.',
    firstSectionId: 'basics',
  },
  {
    id: 'set',
    term: 'Set',
    aliases: ["Set"],
    category: 'Python',
    definition: 'Conjunto sin duplicados. {1, 2, 3}. Operaciones: | unión, & intersección, - diferencia.',
    firstSectionId: 'setup',
  },
  {
    id: 'defaultdict',
    term: 'defaultdict',
    aliases: ["defaultdict"],
    category: 'Python',
    definition: 'Dict que crea valores default automáticamente. from collections import defaultdict.',
    firstSectionId: 'data-structures',
  },
  {
    id: 'counter',
    term: 'Counter',
    aliases: ["Counter"],
    category: 'Python',
    definition: 'Dict especializado para contar. Counter("hola") → {"h":1, "o":1, "l":1, "a":1}.',
    firstSectionId: 'data-structures',
  },
  {
    id: 'namedtuple',
    term: 'namedtuple',
    aliases: ["namedtuple"],
    category: 'Python',
    definition: 'Tuple con campos nombrados. Más legible que índices. from collections import namedtuple.',
    firstSectionId: 'data-structures',
  },
  {
    id: 'ndarray',
    term: 'ndarray',
    aliases: ["ndarray"],
    category: 'NumPy',
    definition: 'Estructura principal de NumPy. Array n-dimensional, todos los elementos del mismo tipo.',
    firstSectionId: 'numpy',
  },
  {
    id: 'vectorizaci-n',
    term: 'Vectorización',
    aliases: ['Vectorización', 'vectorizado', 'vectorized'],
    category: 'NumPy',
    definition: 'Operaciones aplicadas elemento a elemento sin loops de Python. 50-100x más rápido.',
    firstSectionId: 'numpy',
  },
  {
    id: 'broadcasting',
    term: 'Broadcasting',
    aliases: ["Broadcasting"],
    category: 'NumPy',
    definition: 'Permite operar arrays de shapes distintas. NumPy "estira" el más pequeño sin copiar datos.',
    firstSectionId: 'numpy',
  },
  {
    id: 'boolean-masking',
    term: 'Boolean masking',
    aliases: ["Boolean masking"],
    category: 'NumPy',
    definition: 'Usar un array booleano como índice para filtrar. arr[arr > 5] devuelve elementos que cumplen.',
    firstSectionId: 'numpy',
  },
  {
    id: 'shape',
    term: 'Shape',
    aliases: ["Shape"],
    category: 'NumPy',
    definition: 'Dimensiones del array. (3, 4) = 3 filas, 4 columnas. arr.shape devuelve tupla.',
    firstSectionId: 'numpy',
  },
  {
    id: 'dtype',
    term: 'dtype',
    aliases: ["dtype"],
    category: 'NumPy',
    definition: 'Tipo de datos del array. int64, float32, bool, etc. arr.dtype.',
    firstSectionId: 'basics',
  },
  {
    id: 'reshape',
    term: 'Reshape',
    aliases: ["Reshape"],
    category: 'NumPy',
    definition: 'Cambiar la shape sin cambiar los datos. arr.reshape(3, 4). -1 = wildcard.',
    firstSectionId: 'numpy',
  },
  {
    id: 'dataframe',
    term: 'DataFrame',
    aliases: ['DataFrame', 'pd.DataFrame'],
    category: 'Pandas',
    definition: 'Tabla 2D con columnas de tipos distintos. Equivalente a una hoja de Excel. pd.read_csv() lo crea.',
    firstSectionId: 'pandas',
  },
  {
    id: 'series',
    term: 'Series',
    aliases: ['Series', 'pd.Series'],
    category: 'Pandas',
    definition: 'Columna de un DataFrame. 1D con índice. df["col"] devuelve una Series.',
    firstSectionId: 'pandas',
  },
  {
    id: 'groupby',
    term: 'GroupBy',
    aliases: ["GroupBy"],
    category: 'Pandas',
    definition: 'Patrón split-apply-combine. df.groupby("region")["ventas"].sum(). Agrupa por una clave y agrega.',
    firstSectionId: 'pandas',
  },
  {
    id: 'merge',
    term: 'Merge',
    aliases: ["Merge"],
    category: 'Pandas',
    definition: 'Combinar dos DataFrames por una columna común. how: inner, left, right, outer.',
    firstSectionId: 'setup',
  },
  {
    id: 'pivot-table',
    term: 'Pivot table',
    aliases: ["Pivot table"],
    category: 'Pandas',
    definition: 'Reestructura datos largos a anchos. df.pivot_table(index, columns, values, aggfunc).',
    firstSectionId: 'pandas',
  },
  {
    id: 'iloc-vs-loc',
    term: 'iloc vs loc',
    aliases: ["iloc vs loc"],
    category: 'Pandas',
    definition: 'loc usa labels (nombres), iloc usa posiciones (enteros 0-based).',
    firstSectionId: 'pandas',
  },
  {
    id: 'apply',
    term: 'apply',
    aliases: ["apply"],
    category: 'Pandas',
    definition: 'Aplica una función a cada elemento/fila/columna. df["col"].apply(mi_func).',
    firstSectionId: 'data-structures',
  },
  {
    id: 'eda',
    term: 'EDA',
    aliases: ["EDA"],
    category: 'Data Science',
    definition: 'Exploratory Data Analysis. Inspeccionar datos antes de modelar: .info(), .describe(), .value_counts(), visualizaciones.',
    firstSectionId: 'setup',
  },
  {
    id: 'missing-values',
    term: 'Missing values',
    aliases: ['Missing values', 'valores faltantes', 'NaN'],
    category: 'Pandas',
    definition: 'Valores nulos (NaN). isnull().sum() para contar. fillna() para imputar, dropna() para eliminar.',
    firstSectionId: 'pandas',
  },
  {
    id: 'resample',
    term: 'Resample',
    aliases: ["Resample"],
    category: 'Pandas',
    definition: 'Cambiar frecuencia de serie temporal. df.resample("M").sum() agrupa por mes.',
    firstSectionId: 'pandas',
  },
  {
    id: 'pipeline',
    term: 'Pipeline',
    aliases: ["Pipeline"],
    category: 'ML',
    definition: 'Encadena transformaciones + modelo. Evita data leakage. sklearn.pipeline.Pipeline.',
    firstSectionId: 'setup',
  },
  {
    id: 'columntransformer',
    term: 'ColumnTransformer',
    aliases: ["ColumnTransformer"],
    category: 'ML',
    definition: 'Aplica transformaciones distintas a columnas distintas en paralelo. Numéricas: scaler, categóricas: onehot.',
    firstSectionId: 'sklearn',
  },
  {
    id: 'cross-validation',
    term: 'Cross-validation',
    aliases: ['Cross-validation', 'validación cruzada', 'cross_val'],
    category: 'ML',
    definition: 'Divide datos en K folds, entrena en K-1 y evalúa en 1, rotando. cross_val_score. Estratificado para desbalance.',
    firstSectionId: 'sklearn',
  },
  {
    id: 'overfitting',
    term: 'Overfitting',
    aliases: ['Overfitting', 'sobreajuste'],
    category: 'ML',
    definition: 'Modelo memoriza training data, generaliza mal. Síntomas: train score >> test score. Fix: más datos, regularización, simpler model.',
    firstSectionId: 'sklearn',
  },
  {
    id: 'roc-auc',
    term: 'ROC-AUC',
    aliases: ["ROC-AUC"],
    category: 'ML',
    definition: 'Área bajo curva ROC. Métrica para clasificación binaria. 0.5 = azar, 1.0 = perfecto. Robusta a desbalance.',
    firstSectionId: 'sklearn',
  },
  {
    id: 'precision',
    term: 'Precision',
    aliases: ["Precision"],
    category: 'ML',
    definition: 'De los positivos predichos, cuántos son reales. TP / (TP + FP). Alto = pocos falsos positivos.',
    firstSectionId: 'sklearn',
  },
  {
    id: 'recall',
    term: 'Recall',
    aliases: ["Recall"],
    category: 'ML',
    definition: 'De los positivos reales, cuántos detectas. TP / (TP + FN). Alto = pocos falsos negativos.',
    firstSectionId: 'sklearn',
  },
  {
    id: 'f1-score',
    term: 'F1-score',
    aliases: ["F1-score"],
    category: 'ML',
    definition: 'Media armónica de precision y recall. Útil cuando hay desbalance. 2 * (P * R) / (P + R).',
    firstSectionId: 'sklearn',
  },
  {
    id: 'shap',
    term: 'SHAP',
    aliases: ["SHAP"],
    category: 'ML',
    definition: 'SHapley Additive exPlanations. Explica contribución de cada feature a una predicción. Beeswarm global, waterfall individual.',
    firstSectionId: 'numpy',
  },
  {
    id: 'hyperparameter-tuning',
    term: 'Hyperparameter tuning',
    aliases: ["Hyperparameter tuning"],
    category: 'ML',
    definition: 'Encontrar mejores hiperparámetros. GridSearchCV (exhaustivo) o RandomizedSearchCV (más eficiente).',
    firstSectionId: 'sklearn',
  },
  {
    id: 'standardscaler',
    term: 'StandardScaler',
    aliases: ["StandardScaler"],
    category: 'ML',
    definition: 'Normaliza a media 0, std 1. (x - mean) / std. Para modelos sensibles a escala (SVM, regresión).',
    firstSectionId: 'sklearn',
  },
  {
    id: 'onehotencoder',
    term: 'OneHotEncoder',
    aliases: ["OneHotEncoder"],
    category: 'ML',
    definition: 'Convierte categóricas en binarias. drop="first" evita multicolinealidad.',
    firstSectionId: 'sklearn',
  },
  {
    id: 'stratifiedkfold',
    term: 'StratifiedKFold',
    aliases: ["StratifiedKFold"],
    category: 'ML',
    definition: 'KFold que mantiene proporción de clases en cada fold. Obligatorio para clasificación desbalanceada.',
    firstSectionId: 'sklearn',
  },
  {
    id: 'joblib',
    term: 'joblib',
    aliases: ["joblib"],
    category: 'ML',
    definition: 'Persistencia de modelos. joblib.dump(model, "model.joblib"). Más eficiente que pickle para arrays NumPy.',
    firstSectionId: 'sklearn',
  },
  {
    id: 'outlier',
    term: 'Outlier',
    aliases: ["Outlier"],
    category: 'Data Science',
    definition: 'Valor atípico. Detectar con IQR: Q1 - 1.5*IQR a Q3 + 1.5*IQR. Los outliers afectan media y modelos.',
    firstSectionId: 'data-structures',
  },
  {
    id: 'iqr',
    term: 'IQR',
    aliases: ["IQR"],
    category: 'Data Science',
    definition: 'Rango intercuartílico. Q3 - Q1. Medida robusta de dispersión.',
    firstSectionId: 'pandas',
  },
  {
    id: 'correlaci-n',
    term: 'Correlación',
    aliases: ["Correlación"],
    category: 'Data Science',
    definition: 'Relación entre dos variables. -1 a 1. np.corrcoef, df.corr(). Cuidado: correlación no implica causalidad.',
    firstSectionId: 'pandas',
  },
  {
    id: 'distribuci-n-normal',
    term: 'Distribución normal',
    aliases: ["Distribución normal"],
    category: 'Data Science',
    definition: 'Campana de Gauss. Media=mediana=moda. 68% dentro de 1 std, 95% dentro de 2 std.',
    firstSectionId: 'pandas',
  },
  {
    id: 'p-value',
    term: 'p-value',
    aliases: ["p-value"],
    category: 'Data Science',
    definition: 'Probabilidad de observar el resultado si la hipótesis nula es cierta. <0.05 típicamente "significativo".',
    firstSectionId: 'pandas',
  },
  {
    id: 'feature-engineering',
    term: 'Feature engineering',
    aliases: ['Feature engineering', 'ingeniería de features'],
    category: 'Data Science',
    definition: 'Crear nuevas features a partir de las existentes. Ej: año de fecha, ratio de dos columnas, bins de edad.',
    firstSectionId: 'sklearn',
  },
  {
    id: 'train-test-split',
    term: 'Train/test split',
    aliases: ["Train/test split"],
    category: 'ML',
    definition: 'Dividir datos en entrenamiento (80%) y prueba (20%). El modelo nunca "ve" el test durante training.',
    firstSectionId: 'sklearn',
  },
  {
    id: 'data-leakage',
    term: 'Data leakage',
    aliases: ['Data leakage', 'fuga de datos'],
    category: 'ML',
    definition: 'Cuando info del test set "contamina" el entrenamiento. Pipeline lo previene aplicando fit solo en train.',
    firstSectionId: 'sklearn',
  },
  {
    id: 'pyodide',
    term: 'Pyodide',
    aliases: ['pyodide', 'Pyodide'],
    category: 'Tooling',
    definition: 'Python compilado a WebAssembly que corre en el navegador. Permite ejecutar código Python sin instalar nada localmente.',
    firstSectionId: 'setup',
  },
  {
    id: 'rag',
    term: 'RAG',
    aliases: ["retrieval-augmented"],
    category: 'ML',
    definition: 'Retrieval-Augmented Generation: recupera documentos relevantes y los pasa al LLM como contexto para responder con fuentes.',
    firstSectionId: 'setup',
  },
  {
    id: 'mlops',
    term: 'MLOps',
    aliases: ["mlops"],
    category: 'ML',
    definition: 'Prácticas de ingeniería para llevar modelos de ML a producción: versionado, CI/CD, monitoreo y reentrenamiento.',
    firstSectionId: 'rpa-advanced',
  },
  {
    id: 'entity-resolution',
    term: 'Entity resolution',
    aliases: ["entity resolution", "ER", "matching"],
    category: 'Data Science',
    definition: 'Proceso de decidir si dos registros se refieren a la misma entidad del mundo real (sin asumir fraude o parentesco).',
    firstSectionId: 'rpa-automation',
  },
  {
    id: 'fastapi',
    term: 'FastAPI',
    aliases: ["fastapi"],
    category: 'Tooling',
    definition: 'Framework web moderno de Python para APIs HTTP con validación Pydantic y OpenAPI automático.',
    firstSectionId: 'fastapi',
  },
  {
    id: 'streamlit',
    term: 'Streamlit',
    aliases: ["streamlit"],
    category: 'Tooling',
    definition: 'Framework de Python para dashboards interactivos con poco código, útil para demos internas.',
    firstSectionId: 'streamlit-dashboards',
  },
  {
    id: 'llm',
    term: 'LLM',
    aliases: ["llm", "LLMs"],
    category: 'ML',
    definition: 'Large Language Model: modelo de lenguaje de gran escala entrenado para generar y comprender texto.',
    firstSectionId: 'data-acquisition',
  },
  {
    id: 'embedding',
    term: 'Embedding',
    aliases: ["embeddings", "embedding"],
    category: 'ML',
    definition: 'Vector denso que representa significado de texto (o imagen) para búsqueda semántica y clustering.',
    firstSectionId: 'rag',
  },
]

/** Longest-first for safe replace */
export const GLOSSARY_BY_ALIAS: { alias: string; term: GlossaryTerm }[] = GLOSSARY_TERMS
  .flatMap((t) => t.aliases.map((alias) => ({ alias, term: t })))
  .sort((a, b) => b.alias.length - a.alias.length)

export function findGlossaryTerm(query: string): GlossaryTerm | undefined {
  const q = query.trim().toLowerCase()
  return GLOSSARY_TERMS.find(
    (t) => t.term.toLowerCase() === q || t.aliases.some((a) => a.toLowerCase() === q) || t.id === q
  )
}

