#!/usr/bin/env node
/**
 * Regenerate src/assets/setup/index.ts from the PNG captures in that folder.
 *
 *   node scripts/setup_shots_index.mjs           # write
 *   node scripts/setup_shots_index.mjs --check   # exit 1 when index.ts is stale or a capture
 *                                                # has no record in shots.json (and vice versa)
 *
 * Images are imported from src/ rather than served from public/ so the build emits them under
 * _next/static with a content hash and the static export's base path (/pyarcana) applied by
 * Next itself; siteAsset() in src/lib/runtime-mode.ts covers public/ only (PLAN.md §Storage).
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
export const SHOT_DIR = path.join(ROOT, 'src/assets/setup')
const ID = /^[a-z0-9]+(?:-[a-z0-9]+)*$/

/** The index.ts text for a list of capture ids. Pure, for the test. */
export function renderIndex(ids) {
  const sorted = [...ids].sort()
  const name = (id) => `shot_${id.replace(/-/g, '_')}`
  const lines = [
    '// Generated by scripts/setup_shots_index.mjs from the PNG files in this folder. Do not edit by hand:',
    '// add or retake a capture, then run `node scripts/setup_shots_index.mjs`.',
    "import type { StaticImageData } from 'next/image'",
    ...sorted.map((id) => `import ${name(id)} from './${id}.png'`),
    '',
    sorted.length
      ? `export const SHOT_IMAGES: Record<string, StaticImageData> = {\n${sorted.map((id) => `  '${id}': ${name(id)},`).join('\n')}\n}`
      : 'export const SHOT_IMAGES: Record<string, StaticImageData> = {}',
    '',
  ]
  return lines.join('\n')
}

/** Problems that make the folder inconsistent. Pure given the file list and records. */
export function folderProblems(files, records) {
  const problems = []
  const pngs = files.filter((f) => f.endsWith('.png')).map((f) => f.slice(0, -4))
  for (const id of pngs) if (!ID.test(id)) problems.push(`${id}.png: name must be lowercase words joined by "-"`)
  const recIds = new Set(records.map((r) => r.id))
  for (const id of pngs) if (!recIds.has(id)) problems.push(`${id}.png has no record in shots.json (checkedOn, size, box)`)
  for (const id of recIds) if (!pngs.includes(id)) problems.push(`shots.json names ${id} but ${id}.png is missing`)
  return problems
}

function main() {
  const files = readdirSync(SHOT_DIR)
  const records = JSON.parse(readFileSync(path.join(SHOT_DIR, 'shots.json'), 'utf8'))
  const ids = files.filter((f) => f.endsWith('.png') && ID.test(f.slice(0, -4))).map((f) => f.slice(0, -4))
  const want = renderIndex(ids)
  const problems = folderProblems(files, records)
  if (process.argv.includes('--check')) {
    const have = readFileSync(path.join(SHOT_DIR, 'index.ts'), 'utf8')
    if (have !== want) problems.push('src/assets/setup/index.ts is stale: run node scripts/setup_shots_index.mjs')
    for (const p of problems) console.error(`FAIL  ${p}`)
    if (!problems.length) console.log(`OK  ${ids.length} capture(s) indexed`)
    process.exit(problems.length ? 1 : 0)
  }
  writeFileSync(path.join(SHOT_DIR, 'index.ts'), want)
  for (const p of problems) console.error(`WARN  ${p}`)
  console.log(`wrote index.ts with ${ids.length} capture(s)`)
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main()
