// Generated by scripts/setup_shots_index.mjs from the PNG files in this folder. Do not edit by hand:
// add or retake a capture, then run `node scripts/setup_shots_index.mjs`.
import type { StaticImageData } from 'next/image'

export const SHOT_IMAGES: Record<string, StaticImageData> = {}
