// Generated by scripts/setup_shots_index.mjs from the PNG files in this folder. Do not edit by hand:
// add or retake a capture, then run `node scripts/setup_shots_index.mjs`.
import type { StaticImageData } from 'next/image'
import shot_gh_2fa_setup from './gh-2fa-setup.png'
import shot_gh_device_code from './gh-device-code.png'
import shot_gh_noreply_email from './gh-noreply-email.png'
import shot_gh_signup_form from './gh-signup-form.png'
import shot_git_win_download from './git-win-download.png'
import shot_mac_clt_prompt from './mac-clt-prompt.png'
import shot_mac_py_certificates from './mac-py-certificates.png'
import shot_mac_py_installer_done from './mac-py-installer-done.png'
import shot_mac_terminal_open from './mac-terminal-open.png'
import shot_mac_vscode_shell_command from './mac-vscode-shell-command.png'
import shot_py_release_files from './py-release-files.png'
import shot_vscode_terminal from './vscode-terminal.png'
import shot_vscode_trust from './vscode-trust.png'
import shot_win_app_aliases from './win-app-aliases.png'
import shot_win_git_editor from './win-git-editor.png'
import shot_win_py_installer_done from './win-py-installer-done.png'
import shot_win_py_installer_path from './win-py-installer-path.png'
import shot_win_terminal_open from './win-terminal-open.png'
import shot_win_vscode_tasks from './win-vscode-tasks.png'

export const SHOT_IMAGES: Record<string, StaticImageData> = {
  'gh-2fa-setup': shot_gh_2fa_setup,
  'gh-device-code': shot_gh_device_code,
  'gh-noreply-email': shot_gh_noreply_email,
  'gh-signup-form': shot_gh_signup_form,
  'git-win-download': shot_git_win_download,
  'mac-clt-prompt': shot_mac_clt_prompt,
  'mac-py-certificates': shot_mac_py_certificates,
  'mac-py-installer-done': shot_mac_py_installer_done,
  'mac-terminal-open': shot_mac_terminal_open,
  'mac-vscode-shell-command': shot_mac_vscode_shell_command,
  'py-release-files': shot_py_release_files,
  'vscode-terminal': shot_vscode_terminal,
  'vscode-trust': shot_vscode_trust,
  'win-app-aliases': shot_win_app_aliases,
  'win-git-editor': shot_win_git_editor,
  'win-py-installer-done': shot_win_py_installer_done,
  'win-py-installer-path': shot_win_py_installer_path,
  'win-terminal-open': shot_win_terminal_open,
  'win-vscode-tasks': shot_win_vscode_tasks,
}
