// Generated by scripts/setup_shots_index.mjs from the PNG files in this folder. Do not edit by hand:
// add or retake a capture, then run `node scripts/setup_shots_index.mjs`.
import type { StaticImageData } from 'next/image'
import shot_gh_2fa_setup from './gh-2fa-setup.png'
import shot_gh_noreply_email from './gh-noreply-email.png'
import shot_mac_py_certificates from './mac-py-certificates.png'
import shot_mac_py_installer_done from './mac-py-installer-done.png'
import shot_mac_vscode_shell_command from './mac-vscode-shell-command.png'
import shot_vscode_terminal from './vscode-terminal.png'
import shot_vscode_trust from './vscode-trust.png'
import shot_win_py_installer_path from './win-py-installer-path.png'

export const SHOT_IMAGES: Record<string, StaticImageData> = {
  'gh-2fa-setup': shot_gh_2fa_setup,
  'gh-noreply-email': shot_gh_noreply_email,
  'mac-py-certificates': shot_mac_py_certificates,
  'mac-py-installer-done': shot_mac_py_installer_done,
  'mac-vscode-shell-command': shot_mac_vscode_shell_command,
  'vscode-terminal': shot_vscode_terminal,
  'vscode-trust': shot_vscode_trust,
  'win-py-installer-path': shot_win_py_installer_path,
}
